/** YCOS M-02: Premium public-site content only. All copy is synthetic and avoids legal, commercial, client, provider, or partnership claims. */
export const locales = ["ar", "en"] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);

type Card = { title: string; text: string; tag?: string };
type Insight = { slug: string; title: string; excerpt: string; body: string; tag: string };

export type SiteCopy = {
  localeName: string;
  nav: { about: string; services: string; methodology: string; sectors: string; insights: string; contact: string; portal: string; request: string };
  ui: { menu: string; close: string; switchLanguage: string; explore: string; returnHome: string; demonstration: string; notice: string; allServices: string; readInsight: string; backToInsights: string; menuLabel: string };
  footer: { statement: string; legal: string; rights: string; development: string };
  home: { eyebrow: string; title: string; highlight: string; lede: string; primary: string; secondary: string; proofTitle: string; proofText: string; servicesTitle: string; servicesLead: string; methodologyTitle: string; methodologyLead: string; insightTitle: string; insightLead: string };
  about: { eyebrow: string; title: string; lede: string; cards: Card[] };
  services: { eyebrow: string; title: string; lede: string; cards: Card[] };
  methodology: { eyebrow: string; title: string; lede: string; steps: Card[] };
  sectors: { eyebrow: string; title: string; lede: string; cards: Card[] };
  insights: { eyebrow: string; title: string; lede: string; items: Insight[]; empty: string };
  contact: { eyebrow: string; title: string; lede: string; formTitle: string; formLead: string };
  consultation: { eyebrow: string; title: string; lede: string; formTitle: string; formLead: string };
  legal: { privacyTitle: string; termsTitle: string; lede: string; label: string };
  login: { eyebrow: string; title: string; lede: string; action: string };
};

export const siteCopy: Record<Locale, SiteCopy> = {
  ar: {
    localeName: "العربية",
    nav: { about: "عن المنصة", services: "الخدمات", methodology: "المنهجية", sectors: "المجالات", insights: "الرؤى", contact: "التواصل", portal: "مدخل البوابة", request: "طلب استشارة" },
    ui: { menu: "القائمة", close: "إغلاق", switchLanguage: "English", explore: "استكشف البناء", returnHome: "العودة للرئيسية", demonstration: "واجهة تجريبية فقط", notice: "معلومة مهمة", allServices: "عرض إطار الخدمات", readInsight: "قراءة الرؤية", backToInsights: "العودة إلى الرؤى", menuLabel: "التنقل الرئيسي" },
    footer: { statement: "YCOS منصة استشارية تقنية قيد التطوير، تقدم محتوى اصطناعياً لأغراض العرض والتصميم.", legal: "المعلومات القانونية غير معتمدة", rights: "محتوى تجريبي", development: "بُنيت هذه الواجهة كتصور عام فقط." },
    home: { eyebrow: "منصة استشارية تقنية قيد التطوير", title: "نحوّل التعقيد إلى", highlight: "اتجاه واضح", lede: "مساحة عامة لعرض نهج استشاري منظم يجمع الاستراتيجية، التحول الرقمي، والحوكمة التقنية من دون ادعاءات تشغيلية أو تعاقدية.", primary: "استكشف الخدمات", secondary: "تعرف على المنهجية", proofTitle: "بنية مدروسة، لا وعود عامة", proofText: "نصمم لغة موحدة للقرارات، ونرتب نطاق العمل في طبقات قابلة للفهم والمراجعة.", servicesTitle: "مجالات تتكامل حول القرار", servicesLead: "إطار عرضي منظم لخدمات استشارية مقترحة، قابل للتطوير بعد الاعتمادات اللازمة.", methodologyTitle: "منهجية تبدأ بالوضوح", methodologyLead: "رحلة عرضية من أربع محطات تساعد على تنظيم الحوار قبل أي التزام تشغيلي.", insightTitle: "رؤى تجريبية", insightLead: "مواد قصيرة مصطنعة لتوضيح بنية المحتوى المستقبلية فقط." },
    about: { eyebrow: "عن المنصة", title: "مساحة عامة لعرض تفكير منظم", lede: "YCOS تصور لمنصة استشارية تقنية ثنائية اللغة، صممت لتقدم إطاراً واضحاً للخدمات والمنهجية والمحتوى العام.", cards: [{ title: "منطق معماري", text: "نرتب اللغة والخدمات والرحلات ضمن بنية قابلة للقراءة والمراجعة." }, { title: "اتزان ثنائي اللغة", text: "تجربة عربية من اليمين إلى اليسار، وتجربة إنجليزية مكافئة من اليسار إلى اليمين." }, { title: "حدود واضحة", text: "الموقع العام منفصل عن أي بوابة مستقبلية أو بيانات أو تكاملات تشغيلية." }] },
    services: { eyebrow: "إطار الخدمات", title: "سبعة مسارات عرضية للقرار", lede: "هذه المجالات أمثلة تركيبية لعرض اتجاه المنتج، وليست عرضاً تعاقدياً أو التزاماً بتقديم خدمة.", cards: [{ title: "الاستراتيجية", text: "تنظيم الأولويات وخيارات الاتجاه ضمن لغة قرار واضحة.", tag: "01" }, { title: "الاستشارات الإدارية", text: "إطار عمل لتبسيط الأدوار والعمليات ونقاط الاعتماد.", tag: "02" }, { title: "التحول الرقمي", text: "تصور انتقالي يربط التجربة والعمليات والقدرات التقنية.", tag: "03" }, { title: "الذكاء الاصطناعي", text: "إطار حوكمة واستعداد مفاهيمي؛ لا يتضمن موصلاً أو نموذجاً فعلياً.", tag: "04" }, { title: "الأنظمة والمنصات", text: "صياغة حدود المنصات ومسارات القيمة قبل التنفيذ.", tag: "05" }, { title: "التحليلات ولوحات المؤشرات", text: "تصور لقابلية القراءة واتخاذ القرار، دون بيانات أو لوحات تشغيلية.", tag: "06" }, { title: "الحوكمة والعمليات", text: "تنظيم المسؤوليات والضوابط والقرارات المتكررة.", tag: "07" }] },
    methodology: { eyebrow: "المنهجية", title: "من السؤال إلى بنية قابلة للمراجعة", lede: "نهج عرضي غير تعاقدي يوضح كيف يمكن تنظيم العمل الاستشاري قبل تفعيل أي عمليات حقيقية.", steps: [{ title: "01 — التأطير", text: "تحديد السياق والهدف والحدود ونقاط القرار." }, { title: "02 — القراءة", text: "فهم العلاقات والاعتمادات والقيود في صورة مشتركة." }, { title: "03 — التصميم", text: "صياغة بدائل منظمة ومبادئ توجيهية قابلة للنقاش." }, { title: "04 — التفعيل المنضبط", text: "تحديد ما يحتاج قراراً أو اعتماداً قبل التنفيذ." }] },
    sectors: { eyebrow: "المجالات", title: "سياقات نموذجية دون ادعاءات تخصصية", lede: "تستخدم هذه البطاقات محتوى تركيبياً لتوضيح كيفية تنظيم القطاعات ومجالات الخبرة في الموقع.", cards: [{ title: "التعليم", text: "سياق نموذجي لتصميم الخدمات الرقمية والحوكمة المؤسسية." }, { title: "الخدمات المهنية", text: "سياق نموذجي لرحلات العميل ووضوح العمليات." }, { title: "المنظمات النامية", text: "سياق نموذجي لربط الأولويات بالقدرات التشغيلية." }, { title: "المبادرات العامة", text: "سياق نموذجي لتنسيق الأطراف والقرارات والنتائج." }] },
    insights: { eyebrow: "الرؤى", title: "محتوى تجريبي منظم", lede: "نماذج تركيبية توضح طريقة عرض الرؤى دون نسب أو نتائج أو مؤلفين حقيقيين.", empty: "لا توجد رؤى إضافية متاحة في النسخة التجريبية الحالية.", items: [{ slug: "decision-architecture", title: "هندسة القرار تبدأ بتحديد ما يجب ألا يُفترض", excerpt: "نموذج قصير عن فصل الحقائق عن الافتراضات والقرارات المطلوبة.", body: "تساعد بنية القرار على جمع الأسئلة والقيود والاختيارات في صورة قابلة للمراجعة. هذا النص تجريبي ولا يقدم توصية تشغيلية أو قانونية.", tag: "حوكمة" }, { slug: "bilingual-clarity", title: "الوضوح الثنائي اللغة ليس ترجمة حرفية", excerpt: "مادة تجريبية عن التكافؤ المعنوي والاتجاه وتجربة القراءة.", body: "تحتاج التجربة الثنائية اللغة إلى عناوين ومسارات وتسميات متكافئة، مع احترام اختلاف اتجاه القراءة والسياق. المحتوى الحالي لأغراض العرض فقط.", tag: "تجربة" }, { slug: "operating-models", title: "النموذج التشغيلي مساحة لتوضيح العلاقات", excerpt: "عرض تجريبي لكيفية ربط الأدوار والعمليات والقرارات.", body: "يمكن استخدام النماذج التشغيلية لوصف العلاقة بين المسؤوليات ونقاط الاعتماد، من دون افتراض هيكل قائم أو بيانات حقيقية.", tag: "عمليات" }] },
    contact: { eyebrow: "التواصل", title: "واجهة تواصل تجريبية", lede: "هذه الصفحة توضح فقط نموذج تجربة التواصل. لا تُرسل أو تُخزّن أي مدخلات، ولا ينبغي إدخال بيانات حقيقية.", formTitle: "رسالة تجريبية", formLead: "استخدم نصاً افتراضياً فقط. سيظهر تأكيد محلي من دون إرسال." },
    consultation: { eyebrow: "طلب استشارة", title: "تصور لبدء حوار منظم", lede: "واجهة تجريبية لطلب الاستشارة. لا تنشئ طلباً ولا ترسل محتوى إلى بريد أو خادم أو مزود خارجي.", formTitle: "طلب تجريبي", formLead: "يمكن اختبار التحقق المحلي باستخدام بيانات افتراضية فقط." },
    legal: { privacyTitle: "موضع الخصوصية", termsTitle: "موضع الشروط", lede: "هذه مساحة عرض فقط ولا تمثل سياسة خصوصية أو شروطاً ملزمة أو نصاً قانونياً نهائياً.", label: "مراجعة قانونية مطلوبة" },
    login: { eyebrow: "مدخل البوابة", title: "البوابة غير مفعلة في هذه المرحلة", lede: "لا توجد مصادقة أو حسابات أو كلمات مرور أو مزود هوية في هذه الواجهة. التفعيل يحتاج قراراً واعتماداً مستقلاً.", action: "العودة للموقع العام" },
  },
  en: {
    localeName: "English",
    nav: { about: "About", services: "Services", methodology: "Methodology", sectors: "Sectors", insights: "Insights", contact: "Contact", portal: "Portal entry", request: "Request a consultation" },
    ui: { menu: "Menu", close: "Close", switchLanguage: "العربية", explore: "Explore the structure", returnHome: "Return home", demonstration: "Demonstration interface only", notice: "Important notice", allServices: "View service framework", readInsight: "Read insight", backToInsights: "Back to insights", menuLabel: "Primary navigation" },
    footer: { statement: "YCOS is a consulting-technology platform in development. Current content is synthetic and presented for design demonstration.", legal: "Legal information is not approved", rights: "Demonstration content", development: "This interface is a public concept only." },
    home: { eyebrow: "A consulting-technology platform in development", title: "Turn complexity into", highlight: "clear direction", lede: "A public space for presenting a structured consulting approach across strategy, digital transformation, and technology governance—without operational or contractual claims.", primary: "Explore services", secondary: "See the methodology", proofTitle: "Considered structure, not broad promises", proofText: "We shape a shared language for decisions and arrange work into layers that are easier to examine.", servicesTitle: "Fields that converge around the decision", servicesLead: "A structured presentation of proposed consulting domains, ready to evolve only after the required approvals.", methodologyTitle: "A methodology that begins with clarity", methodologyLead: "A four-part public framework for structuring a conversation before any operational commitment.", insightTitle: "Demonstration insights", insightLead: "Short synthetic pieces that illustrate the future content structure only." },
    about: { eyebrow: "About the platform", title: "A public space for structured thinking", lede: "YCOS is a bilingual consulting-technology platform concept designed to present services, methods, and public content with clarity.", cards: [{ title: "Architectural logic", text: "Language, services, and journeys are arranged in structures made to be read and reviewed." }, { title: "Bilingual balance", text: "An RTL Arabic experience and a semantically equivalent LTR English experience." }, { title: "Clear boundaries", text: "The public site remains separate from future portal, data, and operational integrations." }] },
    services: { eyebrow: "Service framework", title: "Seven decision-oriented domains", lede: "These domains are synthetic examples for demonstrating product direction. They are not contractual offerings or commitments.", cards: [{ title: "Strategy", text: "Structure priorities and directional choices in a clear decision language.", tag: "01" }, { title: "Management consulting", text: "A framework for clarifying roles, operations, and dependencies.", tag: "02" }, { title: "Digital transformation", text: "A transition concept linking experience, operations, and technical capability.", tag: "03" }, { title: "Artificial intelligence", text: "A conceptual governance and readiness framework; no adapter or model is active.", tag: "04" }, { title: "Systems and platforms", text: "Shape platform boundaries and value paths before implementation.", tag: "05" }, { title: "Analytics and dashboards", text: "A concept for readability and decision support, without data or live dashboards.", tag: "06" }, { title: "Governance and operations", text: "Organise responsibilities, controls, and recurring decisions.", tag: "07" }] },
    methodology: { eyebrow: "Methodology", title: "From question to reviewable structure", lede: "A non-contractual public approach for organising consulting work before real operations are activated.", steps: [{ title: "01 — Frame", text: "Define context, objective, boundaries, and decision points." }, { title: "02 — Read", text: "See relationships, dependencies, and constraints as a shared picture." }, { title: "03 — Design", text: "Form structured alternatives and principles ready for discussion." }, { title: "04 — Activate carefully", text: "Identify what requires a decision or approval before implementation." }] },
    sectors: { eyebrow: "Sectors", title: "Illustrative contexts, not capability claims", lede: "These cards use synthetic content to show how sectors and domains can be structured on the public site.", cards: [{ title: "Education", text: "An illustrative context for digital service design and institutional governance." }, { title: "Professional services", text: "An illustrative context for client journeys and operational clarity." }, { title: "Growing organisations", text: "An illustrative context for linking priorities with operating capability." }, { title: "Public initiatives", text: "An illustrative context for coordinating parties, decisions, and outcomes." }] },
    insights: { eyebrow: "Insights", title: "Structured demonstration content", lede: "Synthetic examples showing an insight format without real authors, outcomes, or attributions.", empty: "No additional insights are available in the current demonstration release.", items: [{ slug: "decision-architecture", title: "Decision architecture begins with what should not be assumed", excerpt: "A short concept on separating facts, assumptions, and required decisions.", body: "Decision architecture can bring questions, constraints, and options into a reviewable picture. This demonstration text offers no operational or legal recommendation.", tag: "Governance" }, { slug: "bilingual-clarity", title: "Bilingual clarity is not literal translation", excerpt: "A demonstration piece on semantic parity, direction, and reading experience.", body: "A bilingual experience needs equivalent titles, paths, and labels while respecting each reading direction and context. Current content is for demonstration only.", tag: "Experience" }, { slug: "operating-models", title: "An operating model is a space to clarify relationships", excerpt: "A demonstration of linking roles, operations, and decisions.", body: "Operating models can describe the relation between responsibilities and dependencies without assuming an existing structure or real data.", tag: "Operations" }] },
    contact: { eyebrow: "Contact", title: "A demonstration contact interface", lede: "This page only demonstrates the contact experience. No input is sent or stored, and no real data should be entered.", formTitle: "Demonstration message", formLead: "Use placeholder text only. A local confirmation appears without submission." },
    consultation: { eyebrow: "Request a consultation", title: "A concept for starting a structured conversation", lede: "A demonstration consultation request interface. It creates no request and sends no content to email, a server, or an external provider.", formTitle: "Demonstration request", formLead: "Local validation can be tested using placeholder data only." },
    legal: { privacyTitle: "Privacy placeholder", termsTitle: "Terms placeholder", lede: "This is a display placeholder only. It is not a privacy policy, binding terms, or final legal text.", label: "Legal review required" },
    login: { eyebrow: "Portal entry", title: "The portal is not active in this phase", lede: "This interface has no authentication, accounts, passwords, or identity provider. Activation requires an independent decision and approval.", action: "Return to the public site" },
  },
};

export const getCopy = (locale: Locale) => siteCopy[locale];
export const localePath = (locale: Locale, suffix = "") => `/${locale}${suffix}`;
export const oppositeLocale = (locale: Locale): Locale => (locale === "ar" ? "en" : "ar");
export type PageKey = "home" | "about" | "services" | "methodology" | "sectors" | "insights" | "contact" | "consultation" | "privacy" | "terms" | "login" | "insight";
export type RouteDefinition = { key: PageKey; suffix: string; routeId: string; noIndex?: boolean; slug?: string };
export const publicRoutes: RouteDefinition[] = [
  { key: "home", suffix: "", routeId: "R-PUB-01" }, { key: "about", suffix: "/about", routeId: "R-PUB-02" }, { key: "services", suffix: "/services", routeId: "R-PUB-03" }, { key: "methodology", suffix: "/methodology", routeId: "R-PUB-04" }, { key: "sectors", suffix: "/sectors", routeId: "R-PUB-05" }, { key: "insights", suffix: "/insights", routeId: "R-PUB-06" }, { key: "contact", suffix: "/contact", routeId: "R-PUB-08" }, { key: "consultation", suffix: "/request-consultation", routeId: "R-PUB-09" }, { key: "privacy", suffix: "/privacy", routeId: "R-PUB-10" }, { key: "terms", suffix: "/terms", routeId: "R-PUB-11" }, { key: "login", suffix: "/login", routeId: "R-ENT-01", noIndex: true },
];
export const resolveRoute = (segments: string[]): RouteDefinition | undefined => {
  const suffix = `/${segments.join("/")}`;
  const staticRoute = publicRoutes.find((route) => route.suffix === suffix);
  if (staticRoute) return staticRoute;
  if (segments.length === 2 && segments[0] === "insights") return siteCopy.en.insights.items.some((item) => item.slug === segments[1]) ? { key: "insight", suffix, routeId: "R-PUB-07", slug: segments[1] } : undefined;
  return undefined;
};
export const getInsight = (locale: Locale, slug: string) => getCopy(locale).insights.items.find((item) => item.slug === slug);
