import { headers } from "next/headers";
import { e2eScenario } from "@/src/portal/fixtures";
import { authorize, type Resource } from "@/src/portal/policy";
import { m06repo } from "./repository";
import { CommandPanel } from "./command-panel";

type Mode = "requests" | "request" | "engagements" | "projects" | "project" | "work" | "records";
export async function M06Page({ locale, resource, id, mode }: { locale: string; resource: Resource; id?: string; mode: Mode }) {
  const actor = e2eScenario((await headers()).get("x-ycos-e2e-scenario") ?? undefined);
  const rtl = locale === "ar"; const d = authorize(actor, resource); const base = `/${locale}/portal`;
  if (d.effect === "DENY") return <main className="not-found" dir={rtl ? "rtl" : "ltr"}><span className="eyebrow">SYNTHETIC DEMONSTRATION</span><h1>{rtl ? "الوصول غير متاح" : "Access unavailable"}</h1><p>{rtl ? "السياق غير مخول." : "The context is not authorized."}</p></main>;
  const rows: any[] = mode === "requests" ? m06repo.requestsFor(actor!) : mode === "request" ? [m06repo.requestFor(actor!, id ?? "")].filter(Boolean) : mode === "engagements" ? m06repo.engagementsFor(actor!) : mode === "projects" ? m06repo.projectsFor(actor!) : mode === "project" ? [m06repo.projectFor(actor!, id ?? "")].filter(Boolean) : mode === "records" ? m06repo.completedProjectsForRecords(actor!) : m06repo.workFor(actor!, id ?? "");
  const title = rtl ? ({ requests: "طلبات الاستشارة", request: "تفاصيل الطلب", engagements: "الارتباطات", projects: "المشاريع", project: "تفاصيل المشروع", work: "عناصر العمل", records: "سجلات الأرشفة" }[mode]) : ({ requests: "Consultation requests", request: "Request detail", engagements: "Engagements", projects: "Projects", project: "Project detail", work: "Work items", records: "Records archive" }[mode]);
  if (!rows.length) return <main className="not-found" dir={rtl ? "rtl" : "ltr"}><span className="eyebrow">SYNTHETIC DEMONSTRATION</span><h1>{rtl ? "حالة فارغة آمنة" : "Safe empty state"}</h1><p>{rtl ? "المورد غير موجود ضمن نطاقك." : "No resource exists within your scope."}</p></main>;
  const nav = [...(["ROLE-02", "ROLE-03", "ROLE-05"].includes(actor!.role) ? [{ href: `${base}/requests`, label: rtl ? "الطلبات" : "Requests" }] : []), ...(actor!.role === "ROLE-05" ? [{ href: `${base}/engagements`, label: rtl ? "الارتباطات" : "Engagements" }] : []), ...(["ROLE-02", "ROLE-04", "ROLE-05"].includes(actor!.role) ? [{ href: `${base}/projects`, label: rtl ? "المشاريع" : "Projects" }] : []), ...(actor!.role === "ROLE-07" && actor!.recordsAuthority ? [{ href: `${base}/records`, label: rtl ? "سجلات الأرشفة" : "Records archive" }] : [])];
  const kind = mode === "requests" || mode === "request" ? "request" : mode === "engagements" ? "engagement" : mode === "projects" || mode === "project" || mode === "records" ? "project" : "work";
  return <main className="page-main portal-workspace" dir={rtl ? "rtl" : "ltr"}><header className="portal-workspace__header"><b>YCOS</b><span>SYNTHETIC DEMONSTRATION</span></header><div className="portal-workspace__body"><aside className="portal-workspace__sidebar"><p>{rtl ? "تنقل محكوم" : "Governed navigation"}</p>{nav.map(n => <a key={n.href} href={n.href}>{n.label}</a>)}</aside><div><section className="page-hero"><div className="shell section-heading"><nav className="breadcrumbs"><a href={base}>{rtl ? "البوابة" : "Portal"}</a><span>/</span><span>{title}</span></nav><span className="eyebrow">SYNTHETIC DEMONSTRATION</span><h1>{title}</h1><p>{rtl ? "أوامر اصطناعية محكومة؛ لا يترتب عليها التزام فعلي." : "Governed synthetic commands only; no real commitment."}</p></div></section><section className="section" id="command-content"><div className="shell card-grid">{rows.map(x => <article className="editorial-card" key={x.id}><span className="card-mark">{x.id}</span><div><span className="card-tag">{x.state} · v{x.version}</span><h2>{x.title ?? x.name ?? "Synthetic item"}</h2><p>{x.summary ?? x.description ?? "Scoped synthetic resource."}</p></div></article>)}</div><div className="shell"><CommandPanel locale={rtl ? "ar" : "en"} role={actor!.role} kind={kind} rows={rows} projectId={mode === "work" ? id : undefined}/></div></section></div></div></main>;
}
