#!/usr/bin/env bash
# PXSI-01 local-only disposable launch: UI → same-origin API → IAF-01 → PN-03 PostgreSQL. No cloud resource or durable database.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd); BASE=$(mktemp -d /tmp/pxsi01-pg.XXXXXX); sudo chown postgres:postgres "$BASE"; DATA="$BASE/data"; SOCK="$BASE/socket"; PORT=55441; MIGRATION="$BASE/001_work_items.sql"; NEXT_LOG=$(mktemp /tmp/pxsi01-next.XXXXXX.log)
cleanup(){ pkill -P "${NEXT_PID:-0}" >/dev/null 2>&1 || true; kill "${NEXT_PID:-}" >/dev/null 2>&1 || true; pkill -f 'next start.*3011' >/dev/null 2>&1 || true; sudo -u postgres -- /usr/lib/postgresql/16/bin/pg_ctl -D "$DATA" -m immediate stop >/dev/null 2>&1 || true; sudo -u postgres -- rm -rf "$BASE"; rm -f "$NEXT_LOG"; }; trap cleanup EXIT
sudo -u postgres -- mkdir -p "$DATA" "$SOCK"; sudo -u postgres -- chmod 755 "$SOCK"; sudo chmod 711 "$BASE"; sudo cp "$ROOT/infra/pn03/migrations/001_work_items.sql" "$MIGRATION"; sudo chown postgres:postgres "$MIGRATION"
sudo -u postgres -- /usr/lib/postgresql/16/bin/initdb -D "$DATA" -A trust >/dev/null; sudo -u postgres -- /usr/lib/postgresql/16/bin/pg_ctl -D "$DATA" -o "-k $SOCK -p $PORT" -w start >/dev/null
sudo -u postgres -- psql -X -q -h "$SOCK" -p "$PORT" -d postgres -f "$MIGRATION"; sudo -u postgres -- psql -X -q -h "$SOCK" -p "$PORT" -d postgres -c "INSERT INTO work_items VALUES ('W-A','SYNTHETIC_A','draft',1,'synthetic'),('W-B','SYNTHETIC_B','draft',1,'synthetic');"
cd "$ROOT"; pnpm run build >/dev/null; IAF01_PG_SOCKET="$SOCK" IAF01_PG_PORT="$PORT" pnpm exec next start --hostname 127.0.0.1 --port 3011 >"$NEXT_LOG" 2>&1 & NEXT_PID=$!; for _ in $(seq 1 30); do curl -fsS http://127.0.0.1:3011/ar/workspace >/dev/null && break; sleep 1; done; curl --max-time 8 -fsS -H 'x-ycos-local-principal: SYNTHETIC_A' http://127.0.0.1:3011/api/local/workitems; IAF01_PG_SOCKET="$SOCK" IAF01_PG_PORT="$PORT" PXSIBASEURL=http://127.0.0.1:3011 pnpm exec playwright test tests/e2e/pxsi01-postgres.spec.ts tests/e2e/rc-fsv-a11y.spec.ts --config=playwright.pxsi.config.ts --project=chromium
