import { createHash, randomUUID } from 'node:crypto';

const forbiddenKey = /authorization|cookie|password|secret|token|signature|api[_-]?key|connection|string|signed|sas/i;
const forbiddenValue = /(bearer\s+[a-z0-9._~+/=-]+|sig=|se=|sp=|sv=|password=|accountkey=|apikey=|client_secret=|x-ms-signature)/i;
const controlCharacters = /[\u0000-\u001F\u007F]/g;
const safeIdentifier = /^[a-f0-9-]{36}$/i;

export class AuditSecurityError extends Error { constructor(code) { super(code); this.code = code; } }
const canonicalize = (value) => {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])]));
  return value;
};
export const redact = (value, key = '') => {
  if (forbiddenKey.test(key)) return '[REDACTED]';
  if (Array.isArray(value)) return value.map((entry) => redact(entry));
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([entryKey, entryValue]) => [entryKey, redact(entryValue, entryKey)]));
  if (typeof value === 'string') return forbiddenValue.test(value) ? '[REDACTED]' : value.replace(controlCharacters, (char) => `\\u${char.charCodeAt(0).toString(16).padStart(4, '0')}`);
  return value;
};
export const normalizeCorrelation = (candidate) => (typeof candidate === 'string' && safeIdentifier.test(candidate) ? candidate : randomUUID());

export class SyntheticAuditSink {
  constructor({ now = () => new Date(), maxEvents = 500 } = {}) { this.now = now; this.maxEvents = maxEvents; this.events = []; this.previousHash = 'GENESIS'; this.holds = new Set(); }
  append(input) {
    if (this.events.length >= this.maxEvents) throw new AuditSecurityError('AUDIT_BACKPRESSURE_DENIED');
    if (!input?.eventType || !input?.actor?.actorUserId || !input?.actor?.effectiveUserId || !input?.sourceComponent) throw new AuditSecurityError('AUDIT_EVENT_INVALID');
    const event = redact({ eventId: randomUUID(), eventVersion: 1, timestamp: this.now().toISOString(), eventType: input.eventType, actor: input.actor, clientId: input.clientId ?? null, action: input.action ?? null, resource: input.resource ?? null, decision: input.decision ?? null, reasonCode: input.reasonCode ?? null, permission: input.permission ?? null, privilegeContext: input.privilegeContext ?? null, impersonationState: Boolean(input.impersonationState), sessionRef: input.sessionRef ?? null, job: input.job ?? null, correlationId: normalizeCorrelation(input.correlationId), traceId: normalizeCorrelation(input.traceId), sourceComponent: input.sourceComponent, securityClassification: input.securityClassification ?? 'SAFE_OPERATIONAL', result: input.result ?? 'recorded', detail: input.detail ?? {} });
    const serial = JSON.stringify(canonicalize(event)); const eventHash = createHash('sha256').update(`${this.previousHash}|${serial}`).digest('hex'); const stored = Object.freeze({ ...event, sequence: this.events.length + 1, previousHash: this.previousHash, eventHash }); this.events.push(stored); this.previousHash = eventHash; return stored;
  }
  verifyIntegrity() { let previousHash = 'GENESIS'; for (const event of this.events) { const { sequence, previousHash: recordedPrevious, eventHash, ...withoutIntegrity } = event; if (recordedPrevious !== previousHash) return { valid: false, code: 'AUDIT_CHAIN_LINK_INVALID', sequence }; const serial = JSON.stringify(canonicalize(withoutIntegrity)); const expected = createHash('sha256').update(`${previousHash}|${serial}`).digest('hex'); if (expected !== eventHash) return { valid: false, code: 'AUDIT_CHAIN_HASH_INVALID', sequence }; previousHash = eventHash; } return { valid: true, count: this.events.length }; }
  queryClient(context, clientId, exactEventId = undefined) { if (!context?.permissions?.includes('audit.read.client') || context.clientId !== clientId) throw new AuditSecurityError('AUDIT_ACCESS_DENIED'); const rows = this.events.filter((event) => event.clientId === clientId && (!exactEventId || event.eventId === exactEventId)); this.appendAuditOfAudit(context, 'audit.client_query', clientId, { count: rows.length, exactEventId: Boolean(exactEventId) }); return rows; }
  querySecurityInvestigation(context, { purpose, clientId = undefined } = {}) { if (!context?.permissions?.includes('audit.read.security') || !purpose || purpose.length < 3) throw new AuditSecurityError('SECURITY_INVESTIGATION_DENIED'); const rows = this.events.filter((event) => clientId === undefined || event.clientId === clientId); this.appendAuditOfAudit(context, 'audit.security_investigation', clientId ?? null, { purpose, count: rows.length }); return rows; }
  appendAuditOfAudit(context, action, clientId, detail) { return this.append({ eventType: 'audit.access', actor: { actorType: 'user', actorUserId: context.actorUserId, effectiveUserId: context.effectiveUserId }, clientId, action, resource: { type: 'audit_store', id: 'synthetic-local' }, decision: 'ALLOW', reasonCode: 'AUDIT_ACCESS_AUTHORIZED', permission: context.permissions.includes('audit.read.security') ? 'audit.read.security' : 'audit.read.client', correlationId: context.correlationId, sourceComponent: 'ep06-audit-sink', detail }); }
  applyHold(context, eventId, holdReference) { if (!context?.permissions?.includes('audit.admin') || !this.events.some((event) => event.eventId === eventId)) throw new AuditSecurityError('AUDIT_HOLD_DENIED'); this.holds.add(eventId); return this.append({ eventType: 'audit.hold_applied', actor: { actorType: 'user', actorUserId: context.actorUserId, effectiveUserId: context.effectiveUserId }, clientId: context.clientId ?? null, action: 'audit.hold.apply', resource: { type: 'audit_event', id: eventId }, decision: 'ALLOW', reasonCode: 'AUDIT_HOLD_APPLIED', correlationId: context.correlationId, sourceComponent: 'ep06-audit-sink', detail: { holdReference } }); }
  disposition(context, eventId) { if (!context?.permissions?.includes('audit.admin')) throw new AuditSecurityError('AUDIT_DISPOSITION_DENIED'); if (this.holds.has(eventId)) { this.append({ eventType: 'audit.disposition_blocked', actor: { actorType: 'user', actorUserId: context.actorUserId, effectiveUserId: context.effectiveUserId }, clientId: context.clientId ?? null, action: 'audit.disposition', resource: { type: 'audit_event', id: eventId }, decision: 'DENY', reasonCode: 'HOLD_OVERRIDES_DISPOSITION', correlationId: context.correlationId, sourceComponent: 'ep06-audit-sink' }); throw new AuditSecurityError('HOLD_BLOCKED'); } throw new AuditSecurityError('AUDIT_DISPOSITION_NOT_IMPLEMENTED'); }
  metrics() { return Object.fromEntries([...this.events.reduce((map, event) => map.set(event.eventType, (map.get(event.eventType) ?? 0) + 1), new Map())].sort()); }
}

export const auditAuthorizationDecision = (sink, context, { action, resource, decision, reasonCode, permission }) => sink.append({ eventType: 'authorization.decision', actor: { actorType: 'user', actorUserId: context.actorUserId, effectiveUserId: context.effectiveUserId }, clientId: context.clientId, action, resource, decision, reasonCode, permission, correlationId: context.correlationId, sourceComponent: 'ep05-authorization-adapter', impersonationState: context.impersonating, detail: { actorEqualsEffective: context.actorUserId === context.effectiveUserId } });
export const auditObjectAuthority = (sink, context, authority) => sink.append({ eventType: 'storage.authority_issued', actor: { actorType: 'user', actorUserId: context.actorUserId, effectiveUserId: context.effectiveUserId }, clientId: context.clientId, action: authority.payload.operation, resource: { type: 'document', id: authority.payload.documentId }, decision: 'ALLOW', reasonCode: 'OBJECT_AUTHORITY_AUTHORIZED', correlationId: context.correlationId, sourceComponent: 'ep04-object-adapter', detail: { authorityId: createHash('sha256').update(JSON.stringify(authority.payload)).digest('hex').slice(0, 20), expiresAt: authority.payload.expiresAt, operation: authority.payload.operation } });
export const auditIdentityEvent = (sink, context, eventType, detail = {}) => sink.append({ eventType, actor: { actorType: 'user', actorUserId: context.actorUserId, effectiveUserId: context.effectiveUserId }, clientId: context.clientId ?? null, action: eventType, decision: 'ALLOW', reasonCode: 'SYNTHETIC_IDENTITY_EVENT', correlationId: context.correlationId, sourceComponent: 'ep05-identity-adapter', impersonationState: context.actorUserId !== context.effectiveUserId, detail: { synthetic: true, ...detail } });
export const auditBackgroundJob = (sink, { jobId, jobType, clientId, serviceIdentity, initiatorUserId, purpose, correlationId, result }) => sink.append({ eventType: 'job.completed', actor: { actorType: 'service', actorUserId: serviceIdentity, effectiveUserId: serviceIdentity }, clientId, action: jobType, resource: { type: 'job', id: jobId }, decision: result === 'success' ? 'ALLOW' : 'DENY', reasonCode: 'SYNTHETIC_JOB', correlationId, sourceComponent: 'ep06-job-adapter', job: { jobId, jobType, serviceIdentity, initiatorUserId, purpose }, detail: { result } });
