import test from "node:test";
import assert from "node:assert/strict";
import { actors } from "@/src/portal/fixtures";
import { resetM07Repository } from "@/src/m07/repository";
import { transitionApproval, transitionDecision, transitionDeliverable } from "@/src/m07/service";

const fresh = () => resetM07Repository();
test("M07 decision proposal, review, approval, rejection, and safe state/version denial", () => { fresh(); const proposal=transitionDecision(actors.PROJECT_A,"dec-a-01","PROPOSED",1);assert.equal(proposal.ok,true);if(proposal.ok)assert.equal(proposal.value.version,2); const review=transitionDecision(actors.PROJECT_A,"dec-a-01","UNDER_REVIEW",2);assert.equal(review.ok,true); const approval=transitionDecision(actors.MANAGER_A,"dec-a-01","APPROVED",3);assert.equal(approval.ok,true); const stale=transitionDecision(actors.MANAGER_A,"dec-a-01","APPROVED",3);assert.equal(stale.ok,false);if(!stale.ok)assert.equal(stale.error,"VERSION_CONFLICT"); const invalid=transitionDecision(actors.PROJECT_A,"dec-a-01","WITHDRAWN",4);assert.equal(invalid.ok,false);if(!invalid.ok)assert.equal(invalid.error,"STATE_TRANSITION_NOT_ALLOWED"); });
test("M07 decision and approval enforce separation of duties and non-enumerating scope", () => { fresh(); const self=transitionDecision(actors.PROJECT_A,"dec-a-review","APPROVED",1);assert.equal(self.ok,false);if(!self.ok)assert.equal(self.error,"SEPARATION_OF_DUTIES_REQUIRED"); const foreign=transitionDecision(actors.PROJECT_A,"dec-b-01","UNDER_REVIEW",1);assert.equal(foreign.ok,false);if(!foreign.ok)assert.equal(foreign.error,"NOT_FOUND_OR_NOT_AUTHORIZED"); const selfApproval=transitionApproval(actors.PROJECT_A,"apr-a-pending","APPROVED",1);assert.equal(selfApproval.ok,false);if(!selfApproval.ok)assert.equal(selfApproval.error,"SEPARATION_OF_DUTIES_REQUIRED"); const approved=transitionApproval(actors.MANAGER_A,"apr-a-pending","APPROVED",1);assert.equal(approved.ok,true); });
test("M07 approval requester, reviewer, expiry, and version guards remain explicit", () => { fresh(); const withdrawn=transitionApproval(actors.PROJECT_A,"apr-a-01","WITHDRAWN",1);assert.equal(withdrawn.ok,true); fresh(); const pending=transitionApproval(actors.PROJECT_A,"apr-a-01","PENDING",1);assert.equal(pending.ok,true); const invalidWithdrawal=transitionApproval(actors.PROJECT_A,"apr-a-01","WITHDRAWN",2);assert.equal(invalidWithdrawal.ok,false);if(!invalidWithdrawal.ok)assert.equal(invalidWithdrawal.error,"STATE_TRANSITION_NOT_ALLOWED"); const reviewerDenied=transitionApproval(actors.MANAGER_A,"apr-a-01","PENDING",2);assert.equal(reviewerDenied.ok,false); const expired=transitionApproval(actors.OPS_A,"apr-a-pending","EXPIRED",1);assert.equal(expired.ok,true); });
test("M07 deliverables enforce creator, independent approver, delivery, archive authority, scope and version", () => { fresh(); const submit=transitionDeliverable(actors.CONSULTANT_A,"del-a-01","IN_REVIEW",1);assert.equal(submit.ok,true); const approve=transitionDeliverable(actors.MANAGER_A,"del-a-01","APPROVED",2);assert.equal(approve.ok,true); const deliver=transitionDeliverable(actors.PROJECT_A,"del-a-01","DELIVERED",3);assert.equal(deliver.ok,true); const noArchive=transitionDeliverable(actors.PROJECT_A,"del-a-01","ARCHIVED",4);assert.equal(noArchive.ok,false); const foreign=transitionDeliverable(actors.CONSULTANT_A,"del-b-01","IN_REVIEW",1);assert.equal(foreign.ok,false);if(!foreign.ok)assert.equal(foreign.error,"NOT_FOUND_OR_NOT_AUTHORIZED"); });
test("F-M07-01 audit outcomes make success reason-free and denials or conflicts reasoned",()=>{fresh();const allow=transitionDecision(actors.PROJECT_A,"dec-a-01","PROPOSED",1);assert.equal(allow.ok,true);assert.equal("reason"in allow.audit,false);const deny=transitionDecision(actors.PROJECT_A,"dec-b-01","PROPOSED",1);assert.equal(deny.ok,false);assert.equal(deny.audit.outcome,"DENY");assert.equal(deny.audit.reason,"NOT_FOUND_OR_NOT_AUTHORIZED");const conflict=transitionDecision(actors.PROJECT_A,"dec-a-01","UNDER_REVIEW",1);assert.equal(conflict.ok,false);assert.equal(conflict.audit.outcome,"CONFLICT");assert.equal(conflict.audit.reason,"VERSION_CONFLICT");});
