#!/usr/bin/env bash
# RC-FSV-01 LOCAL SYNTHETIC ONLY: clean migration, deterministic state, pg_dump/restore, and relational preservation checks.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd); BASE=$(mktemp -d /tmp/rc-fsv-backup.XXXXXX); DATA="$BASE/data"; SOCK="$BASE/socket"; PORT=55451; BACKUP="$BASE/rc-synthetic.dump"; MIGRATION="$BASE/001_work_items.sql"
cleanup(){ sudo -u postgres -- /usr/lib/postgresql/16/bin/pg_ctl -D "$DATA" -m immediate stop >/dev/null 2>&1 || true; sudo -u postgres -- rm -rf "$BASE"; }; trap cleanup EXIT
sudo chown postgres:postgres "$BASE"; sudo -u postgres -- mkdir -p "$DATA" "$SOCK"; sudo -u postgres -- chmod 755 "$SOCK"; sudo chmod 711 "$BASE"; sudo cp "$ROOT/infra/pn03/migrations/001_work_items.sql" "$MIGRATION"; sudo chown postgres:postgres "$MIGRATION"; sudo -u postgres -- /usr/lib/postgresql/16/bin/initdb -D "$DATA" -A trust >/dev/null; sudo -u postgres -- /usr/lib/postgresql/16/bin/pg_ctl -D "$DATA" -o "-k $SOCK -p $PORT" -w start >/dev/null
sudo -u postgres -- createdb -h "$SOCK" -p "$PORT" rc_source; sudo -u postgres -- psql -X -q -h "$SOCK" -p "$PORT" -d rc_source -f "$MIGRATION"; sudo -u postgres -- psql -X -q -h "$SOCK" -p "$PORT" -d rc_source -c "INSERT INTO work_items VALUES ('RC-A','SYNTHETIC_A','submitted',2,'synthetic'),('RC-B','SYNTHETIC_B','draft',1,'synthetic');"
sudo -u postgres -- pg_dump -Fc -h "$SOCK" -p "$PORT" -d rc_source -f "$BACKUP"; sudo -u postgres -- createdb -h "$SOCK" -p "$PORT" rc_restore; sudo -u postgres -- pg_restore -h "$SOCK" -p "$PORT" -d rc_restore "$BACKUP" >/dev/null
SOURCE=$(sudo -u postgres -- psql -XAt -h "$SOCK" -p "$PORT" -d rc_source -c "SELECT string_agg(tenant_id||':'||id||':'||state||':'||version||':'||classification,',' ORDER BY tenant_id,id) FROM work_items"); RESTORED=$(sudo -u postgres -- psql -XAt -h "$SOCK" -p "$PORT" -d rc_restore -c "SELECT string_agg(tenant_id||':'||id||':'||state||':'||version||':'||classification,',' ORDER BY tenant_id,id) FROM work_items"); test "$SOURCE" = "$RESTORED"; sudo -u postgres -- psql -XAt -h "$SOCK" -p "$PORT" -d rc_restore -c "SELECT conname FROM pg_constraint WHERE conrelid='work_items'::regclass ORDER BY conname" | grep -q 'work_items_pkey'; echo "RC_BACKUP_RESTORE=PASS state=$RESTORED constraints=PASS rls=NOT_APPLICABLE_TO_APPROVED_MIGRATION"
