import { randomUUID } from "node:crypto";
export type TelemetryContext = { actorId: "USER_A" | "CLIENT_ADMIN_A" | "CLIENT_B" | "PLATFORM"; clientId?: "synthetic-client-a" | "synthetic-client-b"; permissions: string[]; correlationId?: string };
type Event = { timestamp: string; name: string; severity: "INFO" | "MEDIUM" | "HIGH"; correlationId: string; operationId: string; actorRef: string; clientId: string | null; component: string; result: string; errorClass?: string; detail: Record<string, unknown> };
const uuid = /^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i; const forbidden = /secret|token|password|authorization|cookie|credential|key|payload|objectcontent/i; const sentinel = /SYNTHETIC_(SECRET|TOKEN|PERSONAL|PAYLOAD)_SENTINEL/i;
export const limits = { maxEvents: 16, maxDetailChars: 96, maxCorrelationChars: 36, maxMetricLabels: 4, alertCooldown: 3 } as const;
export const correlation = (candidate?: string) => typeof candidate === "string" && candidate.length <= limits.maxCorrelationChars && uuid.test(candidate) ? candidate : randomUUID();
const clean = (value: unknown, key = ""): unknown => { if (forbidden.test(key)) return "[REDACTED]"; if (typeof value === "string") return sentinel.test(value) ? "[REDACTED]" : value.replace(/[\u0000-\u001f\u007f]/g, " ").slice(0, limits.maxDetailChars); if (Array.isArray(value)) return value.map(v => clean(v)); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k,v]) => [k, clean(v,k)])); return value; };
export class ObservabilityDomain { events: Event[] = []; metrics = new Map<string, number>(); alerts = new Map<string, { alertId: string; ownerRole: string; runbook: string; count: number; severity: string }>(); dependencies = { audit: true, authorization: true, database: true, object: true, secret: true, telemetry: true }; private emitting = false;
  record(context: TelemetryContext, input: Omit<Event,"timestamp"|"correlationId"|"actorRef"|"clientId"> & { detail?: Record<string,unknown> }) { if (this.emitting || this.events.length >= limits.maxEvents) return { accepted: false, reason: "TELEMETRY_BACKPRESSURE" as const }; this.emitting = true; try { const { detail = {}, ...rest } = input; const event: Event = { timestamp: new Date().toISOString(), correlationId: correlation(context.correlationId), actorRef: context.actorId, clientId: context.clientId ?? null, ...rest, detail: clean(detail) as Record<string,unknown> }; this.events.push(Object.freeze(event)); return { accepted: true, event }; } finally { this.emitting = false; } }
  metric(name: string, labels: Record<string,string> = {}) { const allowed = new Set(["component","outcome","severity","dependency"]); if (Object.keys(labels).length > limits.maxMetricLabels || Object.entries(labels).some(([key,value]) => !allowed.has(key) || value.length > 32 || sentinel.test(value))) throw new Error("METRIC_LABEL_DENIED"); this.metrics.set(`${name}:${JSON.stringify(labels)}`, (this.metrics.get(`${name}:${JSON.stringify(labels)}`) ?? 0) + 1); }
  query(context: TelemetryContext, clientId: string, exactCorrelation?: string) { if (!context.permissions.includes("telemetry.read.client") || context.clientId !== clientId) throw new Error("TELEMETRY_QUERY_DENIED"); return this.events.filter(event => event.clientId === clientId && (!exactCorrelation || event.correlationId === exactCorrelation)); }
  health() { return { live: true, status: "ALIVE", detail: "non-sensitive" }; } readiness() { const mandatory = [this.dependencies.audit,this.dependencies.authorization,this.dependencies.database,this.dependencies.object,this.dependencies.secret]; return { ready: mandatory.every(Boolean), status: mandatory.every(Boolean) ? (this.dependencies.telemetry ? "READY" : "DEGRADED_OPTIONAL_TELEMETRY") : "NOT_READY" }; }
  highRisk(context: TelemetryContext, action: string) { if (!this.dependencies.audit) { this.record(context,{name:"audit.mandatory_unavailable",severity:"HIGH",operationId:action,component:"ep14",result:"DENY",errorClass:"AUDIT_REQUIRED",detail:{}}); return { outcome:"DENY" as const, committed:false }; } return { outcome:"OK" as const, committed:true }; }
  alert(signal: string, scope: string, severity: "MEDIUM"|"HIGH", ownerRole: string, runbook: string) { if (!ownerRole || !runbook) throw new Error("ALERT_OWNER_RUNBOOK_REQUIRED"); const key=`${signal}:${scope}`; const existing=this.alerts.get(key); if(existing){existing.count+=1;return {...existing,deduplicated:true};} const alert={alertId:`ALT-${this.alerts.size+1}`,ownerRole,runbook,count:1,severity};this.alerts.set(key,alert);return {...alert,deduplicated:false}; }
  incidentRecovery() { return { closed:false, reason:"ALERT_RECOVERY_NOT_INCIDENT_CLOSURE" }; }
  scan() { return JSON.stringify({events:this.events,metrics:[...this.metrics],alerts:[...this.alerts]}).match(sentinel)?.[0] ?? null; }
}
