import assert from 'node:assert/strict';
import test from 'node:test';
import { SyntheticAuditSink } from '../../../audit/ep06/src/audit-domain.mjs';
import { PrivacyLifecycleError, SyntheticPrivacyLifecycleDomain } from '../src/privacy-lifecycle-domain.mjs';

const CLIENT_A = '00000000-0000-0000-0000-0000000000a1';
const CLIENT_B = '00000000-0000-0000-0000-0000000000b2';
let clock = 1000;
const ctx = (clientId, permissions) => ({ actorUserId: clientId === CLIENT_A ? '50000000-0000-0000-0000-0000000000a5' : '60000000-0000-0000-0000-0000000000b6', effectiveUserId: clientId === CLIENT_A ? '50000000-0000-0000-0000-0000000000a5' : '60000000-0000-0000-0000-0000000000b6', clientId, permissions, correlationId: '11111111-1111-1111-1111-111111111111' });
const all = ['privacy.record.create','privacy.record.read','privacy.hold.manage','privacy.hold.release','privacy.disposition.request','privacy.disposition.execute','privacy.export.request','privacy.export.authorize','privacy.export.generate','privacy.export.read','privacy.export.revoke','privacy.redaction.execute','privacy.reconcile.execute'];
const denied = (fn, code) => assert.throws(fn, (error) => error instanceof PrivacyLifecycleError && error.code === code);
const setup = () => { clock = 1000; return new SyntheticPrivacyLifecycleDomain({ now: () => clock, auditSink: new SyntheticAuditSink({ now: () => new Date(clock) }), exportLifetimeMs: 50 }); };

test('minimization returns required synthetic fields and omits the sensitive sentinel', () => { const d = setup(); const r = d.createRecord(ctx(CLIENT_A, all), {}); const out = d.viewMinimized(ctx(CLIENT_A, all), r.recordId); assert.equal(out.syntheticSensitive, undefined); assert.equal(out.recordId, r.recordId); });
test('cross-client read, export, disposition, and hold are denied', () => { const d = setup(); const r = d.createRecord(ctx(CLIENT_A, all), {}); denied(() => d.viewMinimized(ctx(CLIENT_B, all), r.recordId), 'PRIVACY_RECORD_NOT_FOUND'); denied(() => d.requestExport(ctx(CLIENT_B, all), r.recordId, { purpose: 'synthetic' }), 'PRIVACY_RECORD_NOT_FOUND'); denied(() => d.requestDisposition(ctx(CLIENT_B, all), r.recordId), 'PRIVACY_RECORD_NOT_FOUND'); denied(() => d.createHold(ctx(CLIENT_B, all), r.recordId, { reasonReference: 'synthetic' }), 'PRIVACY_RECORD_NOT_FOUND'); });
test('hold overrides disposition and release permits controlled disposition', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); const hold = d.createHold(c, r.recordId, { reasonReference: 'synthetic-hold' }); denied(() => d.requestDisposition(c, r.recordId), 'BLOCKED_BY_HOLD'); d.releaseHold(c, hold.holdId); const op = d.requestDisposition(c, r.recordId); assert.equal(d.executeDisposition(c, op.operationId).state, 'DISPOSED'); assert.equal(d.records.get(r.recordId).lifecycle, 'DISPOSED'); });
test('failed disposition remains failed and is not marked disposed', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); const op = d.requestDisposition(c, r.recordId); denied(() => d.executeDisposition(c, op.operationId, { fail: true }), 'DISPOSITION_FAILED'); assert.equal(d.operations.get(op.operationId).state, 'FAILED'); assert.equal(d.records.get(r.recordId).lifecycle, 'ACTIVE'); });
test('restore reconciliation prevents disposed record reactivation and preserves current hold', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); const op = d.requestDisposition(c, r.recordId); d.executeDisposition(c, op.operationId); assert.equal(d.reconcileRestored(c, { ...r, lifecycle: 'ACTIVE' }).lifecycle, 'DISPOSED'); const r2 = d.createRecord(c, {}); const h = d.createHold(c, r2.recordId, { reasonReference: 'synthetic-hold' }); const restored = d.reconcileRestored(c, { ...r2, lifecycle: 'ACTIVE' }); assert.equal(restored.lifecycle, 'HOLD_ACTIVE'); assert.equal(restored.holdId, h.holdId); });
test('authorized export is minimized, private, expires, and exact ID knowledge is not authorization', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); const e = d.requestExport(c, r.recordId, { purpose: 'synthetic-export' }); d.authorizeExport(c, e.exportId); d.generateExport(c, e.exportId); assert.equal(d.readExport(c, e.exportId).syntheticSensitive, undefined); denied(() => d.readExport(ctx(CLIENT_B, all), e.exportId), 'EXPORT_NOT_FOUND'); clock += 60; denied(() => d.readExport(c, e.exportId), 'EXPORT_ACCESS_DENIED'); });
test('export revocation and redaction are enforced', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); const e = d.requestExport(c, r.recordId, { purpose: 'synthetic-export' }); d.authorizeExport(c, e.exportId); d.generateExport(c, e.exportId); d.revokeExport(c, e.exportId); denied(() => d.readExport(c, e.exportId), 'EXPORT_ACCESS_DENIED'); assert.equal(d.redact(c, r.recordId).syntheticSensitive, '[REDACTED]'); });
test('mandatory audit failure blocks high-risk hold and disposition', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); d.auditSink.append = () => { throw new Error('synthetic audit failure'); }; denied(() => d.createHold(c, r.recordId, { reasonReference: 'synthetic-hold' }), 'MANDATORY_AUDIT_UNAVAILABLE'); });
test('audit is privacy-safe, has integrity, and contains no sensitive sentinel', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); d.viewMinimized(c, r.recordId); const joined = JSON.stringify(d.auditSink.events); assert.equal(joined.includes('SYNTHETIC_PRIVATE_SENTINEL'), false); assert.equal(d.auditSink.verifyIntegrity().valid, true); });
test('lineage identifies derived/export state and disposition is idempotent by operation ID', () => { const d = setup(); const c = ctx(CLIENT_A, all); const r = d.createRecord(c, {}); const e = d.requestExport(c, r.recordId, { purpose: 'synthetic-export' }); d.authorizeExport(c, e.exportId); d.generateExport(c, e.exportId); const op = d.requestDisposition(c, r.recordId, 'operation-1'); assert.equal(d.requestDisposition(c, r.recordId, 'operation-1').operationId, op.operationId); assert.equal(d.lineage.get(r.recordId).exports.includes(e.exportId), true); });
