/** M-04 notification contract: known active scoped membership plus constrained inert template variables; never delivery. */
import type { AuthorizationDecision, CorrelationId, Membership, PortResult } from "./types";
import { activeMembership, denied, sameScope } from "./types";
export type NoticeTemplateId = "NOTICE-01" | "NOTICE-02";
export type NoticeResult = Readonly<{ status: "ACCEPTED_FOR_LOCAL_PROCESSING"; idempotencyKey: string }>;
const allowedVariables: Readonly<Record<NoticeTemplateId, readonly string[]>> = { "NOTICE-01": ["resourceLabel", "actionLabel"], "NOTICE-02": ["caseLabel"] };
export const validateSafeVariables = (templateId: NoticeTemplateId, variables: Readonly<Record<string, string>>): boolean => { const permitted = new Set(allowedVariables[templateId]); const entries = Object.entries(variables); return entries.length <= permitted.size && entries.every(([key, value]) => permitted.has(key) && value.length > 0 && value.length <= 120 && !/[\r\n]|\{\{|\}\}|<[^>]+>/u.test(value) && !/(token|secret|password|document|content)/iu.test(key)) && entries.reduce((sum, [, value]) => sum + value.length, 0) <= 256; };
export interface NotificationPort { queueAuthorizedNotice(input: Readonly<{ correlationId: CorrelationId; authorization: AuthorizationDecision; recipient: Membership; templateId: NoticeTemplateId; idempotencyKey: string; safeVariables: Readonly<Record<string, string>> }>): Promise<PortResult<NoticeResult>>; }
export class DisabledNotificationPort { async queueAuthorizedNotice({ correlationId, authorization, recipient, templateId, idempotencyKey, safeVariables }: Readonly<{ correlationId: CorrelationId; authorization: AuthorizationDecision; recipient: Membership; templateId: NoticeTemplateId; idempotencyKey: string; safeVariables: Readonly<Record<string, string>> }>): Promise<PortResult<NoticeResult>> { if (!authorization.allowed || !sameScope(authorization.tenantScope, recipient.scope)) return denied("RECIPIENT_OUT_OF_SCOPE", correlationId); if (!activeMembership(recipient)) return denied("RECIPIENT_INACTIVE", correlationId); if (!/^[a-z0-9][a-z0-9-]{7,63}$/i.test(idempotencyKey)) return denied("INVALID_IDEMPOTENCY_KEY", correlationId); if (!validateSafeVariables(templateId, safeVariables)) return denied("UNSAFE_NOTIFICATION_PAYLOAD", correlationId); return denied("PROVIDER_DISABLED", correlationId); } }
