export const limits = { timeoutMs: 25, maxAttempts: 2, maxQueueDepth: 4, maxWorkerConcurrency: 2, maxHarnessConcurrency: 8, maxHarnessRequests: 64 } as const;
export type Scope = { actorId: "USER_A" | "CLIENT_ADMIN_A" | "CLIENT_B"; clientId: "synthetic-client-a" | "synthetic-client-b"; action: string; objectId: string; correlationId: string; operationId: string; authorityVersion: number };
export type Failure = "TRANSIENT" | "TIMEOUT" | "AUTHORIZATION" | "VALIDATION" | "CONFLICT" | "SECURITY" | "AUDIT" | "SECRET" | "OBJECT" | "DATABASE";
export const retryable = (failure: Failure) => failure === "TRANSIENT" || failure === "TIMEOUT" || failure === "DATABASE" || failure === "OBJECT";
export const boundedRetry = async <T>(scope: Scope, failure: Failure, operation: (attempt: number, trusted: Scope) => Promise<T>): Promise<{ outcome: "OK" | "DENY" | "FAILED"; attempts: number; scope: Scope; value?: T }> => { if (!retryable(failure)) return { outcome: failure === "AUTHORIZATION" || failure === "VALIDATION" || failure === "CONFLICT" || failure === "SECURITY" ? "DENY" : "FAILED", attempts: 1, scope }; for (let attempt = 1; attempt <= limits.maxAttempts; attempt += 1) { try { return { outcome: "OK", attempts: attempt, scope, value: await operation(attempt, scope) }; } catch { if (attempt === limits.maxAttempts) return { outcome: "FAILED", attempts: attempt, scope }; } } return { outcome: "FAILED", attempts: limits.maxAttempts, scope }; };
export class Circuit { private failures = 0; private open = false; call<T>(operation: () => T): { state: "CLOSED" | "OPEN"; value?: T } { if (this.open) return { state: "OPEN" }; try { const value = operation(); this.failures = 0; return { state: "CLOSED", value }; } catch { this.failures += 1; if (this.failures >= 2) this.open = true; return { state: this.open ? "OPEN" : "CLOSED" }; } } reset() { this.failures = 0; this.open = false; } }
type Job = { id: string; scope: Scope; key: string; state: "QUEUED" | "CLAIMED" | "DONE" | "DENIED"; lease?: number };
export class SyntheticQueue { private jobs: Job[] = []; private effects = new Map<string, string>(); private cursor = 0; enqueue(scope: Scope, key: string) { if (this.jobs.length >= limits.maxQueueDepth) return { ok: false as const, reason: "BACKPRESSURE" as const }; if (this.jobs.some(job => job.key === key && job.scope.actorId === scope.actorId && job.scope.clientId === scope.clientId)) return { ok: true as const, duplicate: true as const }; this.jobs.push({ id: `job-${this.jobs.length + 1}`, scope: { ...scope }, key, state: "QUEUED" }); return { ok: true as const, duplicate: false as const }; } claim(now = 1) { const clients = ["synthetic-client-a", "synthetic-client-b"] as const; for (let i = 0; i < clients.length; i += 1) { const clientId = clients[(this.cursor + i) % clients.length]; const job = this.jobs.find(value => value.state === "QUEUED" && value.scope.clientId === clientId); if (job) { this.cursor = (this.cursor + i + 1) % clients.length; job.state = "CLAIMED"; job.lease = now + 1; return job; } } return undefined; } execute(job: Job, currentAuthority: (scope: Scope) => boolean, now = 1) { if (job.state !== "CLAIMED" || !job.lease || now > job.lease || !currentAuthority(job.scope)) { job.state = "DENIED"; return { ok: false as const, reason: "CURRENT_AUTHORITY_REQUIRED" as const }; } const effectKey = `${job.scope.actorId}:${job.scope.clientId}:${job.scope.action}:${job.key}`; if (this.effects.has(effectKey)) { job.state = "DONE"; return { ok: true as const, duplicate: true as const, effect: this.effects.get(effectKey) }; } const effect = `effect-${this.effects.size + 1}`; this.effects.set(effectKey, effect); job.state = "DONE"; return { ok: true as const, duplicate: false as const, effect }; } recoverExpired(now = 2) { for (const job of this.jobs) if (job.state === "CLAIMED" && (job.lease ?? 0) < now) job.state = "QUEUED"; } snapshot() { return this.jobs.map(job => ({ ...job, scope: { ...job.scope } })); } }
export class ResilienceState { mandatory = { audit: true, authorization: true, database: true, secret: true, object: true }; optional = { telemetry: true }; shuttingDown = false; auditRequired(action: string) { return ["EXPORT", "DISPOSITION", "PRIVILEGED"].includes(action); } readiness() { return Object.values(this.mandatory).every(Boolean) && !this.shuttingDown; } execute(scope: Scope, failure?: Failure) { if (this.shuttingDown) return { outcome: "DENY" as const, reason: "SHUTTING_DOWN" }; if (!this.mandatory.authorization) return { outcome: "DENY" as const, reason: "AUTHORIZATION_UNAVAILABLE" }; if (this.auditRequired(scope.action) && !this.mandatory.audit) return { outcome: "DENY" as const, reason: "AUDIT_REQUIRED" }; if (failure === "SECRET" || failure === "OBJECT" || failure === "DATABASE") return { outcome: "FAILED" as const, reason: `${failure}_CONTROLLED_FAILURE` }; return { outcome: "OK" as const, reason: this.optional.telemetry ? "OK" : "DEGRADED_OPTIONAL_TELEMETRY" }; } }
