import { headers } from "next/headers";
import { e2eScenario } from "@/src/portal/fixtures";
import { authorize, type Resource } from "@/src/portal/policy";
import { m07repo } from "./repository";
import { M07CommandPanel } from "./command-panel";

type Mode = "decisions" | "decision" | "approvals" | "deliverables" | "deliverable" | "audit";
function M07Denied({ ar }: { ar: boolean }) { return <main className="m07-denied" dir={ar ? "rtl" : "ltr"}><header className="m07-denied__bar"><div className="m07-brand"><strong>YCOS</strong><span>{ar ? "منظومة القرارات المحكومة" : "Governed decision system"}</span></div><span className="m07-denied__code">AUTH / 403</span></header><section className="m07-denied__grid"><aside><span className="m07-denied__index">07</span><span>{ar ? "سياق تشغيلي" : "Operational context"}</span></aside><div><span className="eyebrow">SYNTHETIC DEMONSTRATION</span><h1>{ar ? "القرار محكوم" : "Decision access is governed"}</h1><p>{ar ? "لم تُشتق سلطة صالحة لهذا المورد ضمن السياق الحالي. راجع مسار البوابة المخوّل أو اطلب نطاقاً معتمداً." : "No valid authority was derived for this resource. Return to an authorized portal path or request an approved scope."}</p><a className="m07-denied__return" href={ar ? "/ar/portal" : "/en/portal"}>{ar ? "العودة إلى البوابة" : "Return to portal"}</a></div></section></main> }
export async function M07Page({ locale, resource, mode, id }: { locale: string; resource: Resource; mode: Mode; id?: string }) {
  const actor = e2eScenario((await headers()).get("x-ycos-e2e-scenario") ?? undefined); const ar = locale === "ar";
  if (authorize(actor, resource, "m07-page").effect === "DENY") return <M07Denied ar={ar}/>;
  const rows: any[] = mode === "decisions" ? [...m07repo.decisionsFor(actor!)] : mode === "decision" ? [m07repo.decisionFor(actor!, id ?? "")].filter(Boolean) : mode === "approvals" ? m07repo.approvalsFor(actor!) : mode === "deliverables" ? [...m07repo.deliverablesFor(actor!)] : mode === "deliverable" ? [m07repo.deliverableFor(actor!, id ?? "")].filter(Boolean) : [];
  const title = ar ? ({ decisions: "القرارات", decision: "تفاصيل القرار", approvals: "الموافقات", deliverables: "المخرجات", deliverable: "تفاصيل المخرج", audit: "سجل التدقيق" }[mode]) : ({ decisions: "Decisions", decision: "Decision detail", approvals: "Approvals", deliverables: "Deliverables", deliverable: "Deliverable detail", audit: "Audit log" }[mode]); const base = `/${locale}/portal`;
  const nav = [...(actor!.role === "ROLE-05" || actor!.role === "ROLE-03" ? [{ href: `${base}/decisions`, label: ar ? "القرارات" : "Decisions" }, { href: `${base}/approvals`, label: ar ? "الموافقات" : "Approvals" }] : []), ...(["ROLE-03", "ROLE-04", "ROLE-05", "ROLE-07"].includes(actor!.role) ? [{ href: `${base}/deliverables`, label: ar ? "المخرجات" : "Deliverables" }] : []), ...(actor!.role === "ROLE-08" ? [{ href: `${base}/audit`, label: ar ? "سجل التدقيق" : "Audit log" }] : [])];
  if (mode !== "audit" && !rows.length) return <M07Denied ar={ar}/>;
  const auditRows = mode === "audit" ? [{ id: "audit-a-01", state: "ALLOW", version: 1, title: "M07_COMMAND · DECISION · minimal intent" }, { id: "audit-a-02", state: "DENY", version: 1, title: "M07_COMMAND · APPROVAL · minimal intent" }] : rows; const kind = mode.startsWith("decision") ? "decision" : mode === "approvals" ? "approval" : "deliverable";
  return <main className="page-main portal-workspace" dir={ar ? "rtl" : "ltr"}><header className="portal-workspace__header"><b>YCOS</b><span>SYNTHETIC DEMONSTRATION</span></header><div className="portal-workspace__body"><aside className="portal-workspace__sidebar"><p>{ar ? "تنقل محكوم" : "Governed navigation"}</p>{nav.map(item => <a key={item.href} href={item.href}>{item.label}</a>)}</aside><div><section className="page-hero"><div className="shell section-heading"><nav className="breadcrumbs"><a href={base}>{ar ? "البوابة" : "Portal"}</a><span>/</span><span>{title}</span></nav><span className="eyebrow">SYNTHETIC DEMONSTRATION</span><h1>{title}</h1><p>{ar ? "مسارات قرار وموافقة ومخرج تركيبية، محكومة خادمياً." : "Synthetic decision, approval, and deliverable paths governed server-side."}</p></div></section><section className="section"><div className="shell card-grid">{auditRows.map(row => <article className="editorial-card" key={row.id}><span className="card-mark">{row.id}</span><div><span className="card-tag">{row.state} · v{row.version}</span><h2>{row.title}</h2><p>{mode === "audit" ? (ar ? "نية تدقيق مختصرة؛ لا محتوى أو أسرار." : "Minimal audit intent; no content or secrets.") : (ar ? "مورد اصطناعي ضمن نطاق مشتق." : "Synthetic resource within derived scope.")}</p></div></article>)}</div>{mode !== "audit" && <div className="shell"><M07CommandPanel locale={ar ? "ar" : "en"} kind={kind as any} role={actor!.role} rows={rows}/></div>}</section></div></div></main>;
}
