import assert from 'node:assert/strict'; import test from 'node:test'; import { SyntheticDocumentStorage, StorageSecurityError } from '../src/document-storage-domain.mjs';
const CLIENT_A = '00000000-0000-0000-0000-0000000000a1'; const CLIENT_B = '00000000-0000-0000-0000-0000000000b2'; const bytes = (label) => Buffer.from(`SYNTHETIC:${label}`, 'utf8');
async function createAvailable(store, clientId, label) { const doc = store.createDocument(clientId, { originalFilename: `${label}.txt`, declaredContentType: 'text/plain', declaredSize: bytes(label).length }); await store.writeWithAuthority(clientId, store.requestUpload(clientId, doc.documentId), bytes(label)); return store.completeUpload(clientId, doc.documentId, 'SIMULATED_CLEAN'); }
async function setup(options = {}) { const store = new SyntheticDocumentStorage(options); await store.initialize(); return { store, a: await createAvailable(store, CLIENT_A, 'a-object'), b: await createAvailable(store, CLIENT_B, 'b-object') }; }
async function expectCode(action, code) { let received; try { await action(); } catch (error) { received = error; } assert.ok(received instanceof StorageSecurityError && received.code === code, `expected ${code}, received ${received?.code ?? 'no error'}`); }
test('CLIENT_A own upload complete read metadata delete passes', async (t) => { const store = new SyntheticDocumentStorage(); await store.initialize(); t.after(() => store.cleanup()); const doc = store.createDocument(CLIENT_A, { originalFilename: 'own.txt', declaredContentType: 'text/plain', declaredSize: bytes('own').length }); await store.writeWithAuthority(CLIENT_A, store.requestUpload(CLIENT_A, doc.documentId), bytes('own')); assert.equal(store.completeUpload(CLIENT_A, doc.documentId, 'SIMULATED_CLEAN').securityStatus, 'available'); assert.equal((await store.readWithAuthority(CLIENT_A, store.requestDownload(CLIENT_A, doc.documentId))).toString(), 'SYNTHETIC:own'); await store.deleteWithAuthority(CLIENT_A, store.requestDelete(CLIENT_A, doc.documentId)); await expectCode(() => Promise.resolve(store.getMetadata(CLIENT_A, doc.documentId)), 'DOCUMENT_NOT_FOUND'); });
test('CLIENT_B equivalent behavior passes', async (t) => { const store = new SyntheticDocumentStorage(); await store.initialize(); t.after(() => store.cleanup()); const doc = await createAvailable(store, CLIENT_B, 'own-b'); assert.equal((await store.readWithAuthority(CLIENT_B, store.requestDownload(CLIENT_B, doc.documentId))).toString(), 'SYNTHETIC:own-b'); });
test('cross-client read and metadata are non-disclosing', async (t) => { const { store, b } = await setup(); t.after(() => store.cleanup()); await expectCode(() => Promise.resolve(store.getMetadata(CLIENT_A, b.documentId)), 'DOCUMENT_NOT_FOUND'); await expectCode(() => Promise.resolve(store.requestDownload(CLIENT_A, b.documentId)), 'DOCUMENT_NOT_FOUND'); });
test('cross-client write, overwrite, and delete are denied', async (t) => { const { store, b } = await setup(); t.after(() => store.cleanup()); const authority = store.issueAuthority(CLIENT_B, store.requireDocument(b.documentId), 'upload'); await expectCode(() => store.writeWithAuthority(CLIENT_A, authority, bytes('attack')), 'AUTHORITY_DENIED'); assert.throws(() => store.createDocument(CLIENT_A, { originalFilename: 'x.txt', declaredContentType: 'text/plain', declaredSize: 16, objectKey: b.objectKey }), { code: 'CALLER_OBJECT_KEY_DENIED' }); assert.throws(() => store.unsafeWriteByObjectKey(CLIENT_A, b.objectKey, bytes('attack')), { code: 'DIRECT_OBJECT_KEY_ACCESS_DENIED' }); await expectCode(() => Promise.resolve(store.requestDelete(CLIENT_A, b.documentId)), 'DOCUMENT_NOT_FOUND'); });
test('cross-client discovery through metadata and storage listing is denied', async (t) => { const { store, b } = await setup(); t.after(() => store.cleanup()); assert.equal(store.listMetadata(CLIENT_A).some((d) => d.documentId === b.documentId), false); assert.throws(() => store.listStorage(CLIENT_A), { code: 'STORAGE_LISTING_DENIED' }); });
test('authority is object, operation, client, and expiry scoped', async (t) => { let time = 10; const { store, a, b } = await setup({ now: () => time, authorityLifetimeMs: 5 }); t.after(() => store.cleanup()); const read = store.requestDownload(CLIENT_A, a.documentId); const tampered = { payload: { ...read.payload, documentId: b.documentId, objectKey: b.objectKey }, signature: read.signature }; await expectCode(() => store.readWithAuthority(CLIENT_A, tampered), 'AUTHORITY_INVALID'); await expectCode(() => store.deleteWithAuthority(CLIENT_A, read), 'AUTHORITY_DENIED'); await expectCode(() => store.readWithAuthority(CLIENT_B, read), 'AUTHORITY_DENIED'); time = 16; await expectCode(() => store.readWithAuthority(CLIENT_A, read), 'AUTHORITY_DENIED'); });
test('state and validation failure fail closed', async (t) => { const store = new SyntheticDocumentStorage(); await store.initialize(); t.after(() => store.cleanup()); const doc = store.createDocument(CLIENT_A, { originalFilename: 'pending.txt', declaredContentType: 'text/plain', declaredSize: 16 }); await expectCode(() => Promise.resolve(store.requestDownload(CLIENT_A, doc.documentId)), 'DOWNLOAD_STATE_DENIED'); await store.writeWithAuthority(CLIENT_A, store.requestUpload(CLIENT_A, doc.documentId), bytes('state')); assert.equal(store.completeUpload(CLIENT_A, doc.documentId, 'SIMULATED_UNKNOWN').securityStatus, 'quarantined'); await expectCode(() => Promise.resolve(store.requestDownload(CLIENT_A, doc.documentId)), 'DOWNLOAD_STATE_DENIED'); });
test('type, size, filename, traversal, and hold boundaries are enforced', async (t) => { const store = new SyntheticDocumentStorage({ maxBytes: 20 }); await store.initialize(); t.after(() => store.cleanup()); assert.throws(() => store.createDocument(CLIENT_A, { originalFilename: 'bad.html', declaredContentType: 'text/html', declaredSize: 10 }), { code: 'DECLARED_TYPE_REJECTED' }); for (const name of ['../secret', '..\\secret', '/absolute.txt', '%2e%2e%2fsecret', 'bad\r\nheader.txt', 'dir/name.txt']) assert.throws(() => store.createDocument(CLIENT_A, { originalFilename: name, declaredContentType: 'text/plain', declaredSize: 10 }), { code: 'FILENAME_REJECTED' }); const held = await createAvailable(store, CLIENT_A, 'held'); store.applySyntheticHold(held.documentId, 'SYNTHETIC-HOLD-01'); await expectCode(() => Promise.resolve(store.requestDelete(CLIENT_A, held.documentId)), 'DELETE_DENIED'); });
test('audit events do not contain temporary authority material', async (t) => { const { store, a } = await setup(); t.after(() => store.cleanup()); store.requestDownload(CLIENT_A, a.documentId); assert.equal(JSON.stringify(store.auditEvents).includes('signature'), false); });
