import { createHmac, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';

export const CLIENT_A = '00000000-0000-0000-0000-0000000000a1';
export const CLIENT_B = '00000000-0000-0000-0000-0000000000b2';
export const CLIENT_C = '00000000-0000-0000-0000-0000000000c3';
export const USER_A = '50000000-0000-0000-0000-0000000000a5';
export const USER_B = '60000000-0000-0000-0000-0000000000b6';
export const ADMIN_A = '70000000-0000-0000-0000-0000000000c7';
export const SUPPORT_A = '80000000-0000-0000-0000-0000000000d8';
export const BREAK_GLASS_A = '90000000-0000-0000-0000-0000000000e9';
const permissionMap = { CLIENT_MEMBER: ['case.read', 'document.read'], CLIENT_CASE_MANAGER: ['case.read', 'case.update'], CLIENT_DOCUMENT_MANAGER: ['document.read', 'document.upload', 'document.delete'], CLIENT_ADMIN: ['client.manage_members'], PLATFORM_CONFIG_ADMIN: ['platform.config.manage'], PRIVILEGED_SUPPORT: ['privileged.support'], BREAK_GLASS_OPERATOR: ['breakglass.activate'] };
const restrictedDuringImpersonation = new Set(['client.manage_members', 'role.assign', 'permission.modify', 'breakglass.activate', 'security.manage', 'delete.admin']);
export class AuthorizationError extends Error { constructor(code) { super(code); this.code = code; } }

export class SyntheticAuthorizationDomain {
  constructor({ now = () => Date.now(), sessionLifetimeMs = 60000, elevationLifetimeMs = 30000 } = {}) {
    this.now = now; this.sessionLifetimeMs = sessionLifetimeMs; this.elevationLifetimeMs = elevationLifetimeMs; this.secret = randomBytes(32); this.sessions = new Map(); this.auditEvents = [];
    this.users = new Map([[USER_A,{ state:'active' }],[USER_B,{ state:'active' }],[ADMIN_A,{ state:'active' }],[SUPPORT_A,{ state:'active' }],[BREAK_GLASS_A,{ state:'active' }]]);
    this.external = new Map([['SYNTHETIC_ISSUER|SUBJECT_USER_A',USER_A],['SYNTHETIC_ISSUER|SUBJECT_USER_B',USER_B],['SYNTHETIC_ISSUER|SUBJECT_ADMIN_A',ADMIN_A],['SYNTHETIC_ISSUER|SUBJECT_SUPPORT_A',SUPPORT_A],['SYNTHETIC_ISSUER|SUBJECT_BREAK_GLASS_A',BREAK_GLASS_A]]);
    this.memberships = new Map([[`${USER_A}|${CLIENT_A}`,{state:'active'}],[`${USER_A}|${CLIENT_B}`,{state:'active'}],[`${USER_B}|${CLIENT_B}`,{state:'active'}],[`${ADMIN_A}|${CLIENT_A}`,{state:'active'}],[`${SUPPORT_A}|${CLIENT_A}`,{state:'active'}],[`${BREAK_GLASS_A}|${CLIENT_A}`,{state:'active'}]]);
    this.roles = new Map([[`${USER_A}|${CLIENT_A}`,new Set(['CLIENT_DOCUMENT_MANAGER','CLIENT_MEMBER'])],[`${USER_A}|${CLIENT_B}`,new Set(['CLIENT_MEMBER'])],[`${USER_B}|${CLIENT_B}`,new Set(['CLIENT_MEMBER'])],[`${ADMIN_A}|${CLIENT_A}`,new Set(['CLIENT_ADMIN'])],[`${SUPPORT_A}|${CLIENT_A}`,new Set(['CLIENT_MEMBER'])],[`${SUPPORT_A}|platform`,new Set(['PRIVILEGED_SUPPORT'])],[`${BREAK_GLASS_A}|platform`,new Set(['BREAK_GLASS_OPERATOR'])]]);
  }
  authenticateSynthetic({ issuer, subject }) { const userId = this.external.get(`${issuer}|${subject}`); if (!userId || this.userState(userId) !== 'active') throw new AuthorizationError('AUTHENTICATION_DENIED'); const clientId = this.firstActiveMembership(userId); if (!clientId) throw new AuthorizationError('NO_ACTIVE_CLIENT_MEMBERSHIP'); return this.newSession(userId, clientId); }
  newSession(userId, clientId) { const sessionId = randomUUID(); const record = { sessionId, actorUserId:userId, effectiveUserId:userId, activeClientId:clientId, issuedAt:this.now(), expiresAt:this.now()+this.sessionLifetimeMs, revoked:false, generation:1, impersonation:null, breakGlass:null }; this.sessions.set(sessionId, record); this.audit('login_success', record, { clientId }); return this.signEnvelope(record); }
  signEnvelope(record) { const payload={sessionId:record.sessionId, issuedAt:record.issuedAt, expiresAt:record.expiresAt, generation:record.generation}; const encoded=JSON.stringify(payload); return { payload, signature:createHmac('sha256',this.secret).update(encoded).digest('hex') }; }
  parseSession(envelope) { if(!envelope?.payload||typeof envelope.signature!=='string') throw new AuthorizationError('SESSION_INVALID'); const encoded=JSON.stringify(envelope.payload); const expected=createHmac('sha256',this.secret).update(encoded).digest('hex'); if(envelope.signature.length!==expected.length||!timingSafeEqual(Buffer.from(envelope.signature),Buffer.from(expected))) throw new AuthorizationError('SESSION_TAMPERED'); const record=this.sessions.get(envelope.payload.sessionId); if(!record||record.revoked||record.generation!==envelope.payload.generation||record.expiresAt!==envelope.payload.expiresAt||record.expiresAt<=this.now()) throw new AuthorizationError('SESSION_DENIED'); if(this.userState(record.actorUserId)!=='active'||this.userState(record.effectiveUserId)!=='active') throw new AuthorizationError('SESSION_DENIED'); return record; }
  switchClient(envelope,targetClientId) { const record=this.parseSession(envelope); if(record.impersonation) throw new AuthorizationError('SWITCH_DURING_IMPERSONATION_DENIED'); if(!this.isActiveMembership(record.effectiveUserId,targetClientId)) throw new AuthorizationError('CLIENT_SWITCH_DENIED'); record.activeClientId=targetClientId; record.generation++; this.audit('client_switch',record,{targetClientId}); return this.signEnvelope(record); }
  authorize(envelope,action,{resourceClientId}={}) { const record=this.parseSession(envelope); const clientId=record.activeClientId; if(resourceClientId&&resourceClientId!==clientId) throw new AuthorizationError('RESOURCE_CLIENT_DENIED'); if(!this.isActiveMembership(record.effectiveUserId,clientId)) throw new AuthorizationError('MEMBERSHIP_DENIED'); if(record.impersonation&&record.impersonation.expiresAt<=this.now()) { record.effectiveUserId=record.actorUserId; record.impersonation=null; this.audit('impersonation_expired',record); }
    if(record.impersonation&&restrictedDuringImpersonation.has(action)) throw new AuthorizationError('IMPERSONATION_RESTRICTED'); const permissions=this.permissions(record.effectiveUserId,clientId); if(!permissions.has(action)) throw new AuthorizationError('AUTHORIZATION_DENIED'); this.audit('authorization_allow',record,{action,clientId}); return { actorUserId:record.actorUserId,effectiveUserId:record.effectiveUserId,clientId,permissions:[...permissions],correlationId:randomUUID(),impersonating:Boolean(record.impersonation) }; }
  authorizeFromUntrustedRequest(envelope,{requestedClientId,action,resourceClientId}) { const record=this.parseSession(envelope); if(requestedClientId!==undefined&&requestedClientId!==record.activeClientId) throw new AuthorizationError('UNTRUSTED_CLIENT_SCOPE_DENIED'); return this.authorize(envelope,action,{resourceClientId}); }
  authorizeDatabaseAction(envelope,action,resourceClientId) { const context=this.authorize(envelope,action,{resourceClientId}); return { ...context, transactionLocalClientId:context.clientId }; }
  authorizeDocumentRead(envelope,storage,documentId) { const context=this.authorize(envelope,'document.read'); storage.getMetadata(context.clientId,documentId); return storage.requestDownload(context.clientId,documentId); }
  assignClientRole(envelope,{targetUserId,clientId,roleCode}) { const context=this.authorize(envelope,'client.manage_members',{resourceClientId:clientId}); if(context.actorUserId===targetUserId||context.effectiveUserId===targetUserId) throw new AuthorizationError('SELF_ESCALATION_DENIED'); if(!permissionMap[roleCode]||['PLATFORM_CONFIG_ADMIN','PRIVILEGED_SUPPORT','BREAK_GLASS_OPERATOR'].includes(roleCode)) throw new AuthorizationError('ROLE_ASSIGNMENT_DENIED'); if(!this.isActiveMembership(targetUserId,clientId)) throw new AuthorizationError('ROLE_ASSIGNMENT_DENIED'); const key=`${targetUserId}|${clientId}`; if(!this.roles.has(key)) this.roles.set(key,new Set()); this.roles.get(key).add(roleCode); this.audit('role_assignment',this.parseSession(envelope),{targetUserId,clientId,roleCode}); }
  startImpersonation(envelope,{targetUserId,reason}) { const record=this.parseSession(envelope); if(!this.permissions(record.actorUserId,record.activeClientId).has('privileged.support')) throw new AuthorizationError('IMPERSONATION_DENIED'); if(!reason||reason.trim().length<3||!this.isActiveMembership(targetUserId,record.activeClientId)) throw new AuthorizationError('IMPERSONATION_DENIED'); record.effectiveUserId=targetUserId; record.impersonation={targetUserId,reason,expiresAt:this.now()+this.elevationLifetimeMs,correlationId:randomUUID()}; record.generation++; this.audit('impersonation_start',record,{reason}); return this.signEnvelope(record); }
  endImpersonation(envelope) { const record=this.parseSession(envelope); if(!record.impersonation) throw new AuthorizationError('IMPERSONATION_NOT_ACTIVE'); this.audit('impersonation_end',record,{reason:record.impersonation.reason}); record.effectiveUserId=record.actorUserId; record.impersonation=null; record.generation++; return this.signEnvelope(record); }
  startBreakGlass(envelope,{reason}) { const record=this.parseSession(envelope); if(record.impersonation||!this.permissions(record.actorUserId,record.activeClientId).has('breakglass.activate')||!reason||reason.trim().length<3) throw new AuthorizationError('BREAK_GLASS_DENIED'); record.breakGlass={reason,expiresAt:this.now()+this.elevationLifetimeMs,correlationId:randomUUID()}; record.generation++; this.audit('break_glass_start',record,{reason}); return this.signEnvelope(record); }
  endBreakGlass(envelope) { const record=this.parseSession(envelope); if(!record.breakGlass) throw new AuthorizationError('BREAK_GLASS_NOT_ACTIVE'); this.audit('break_glass_end',record,{reason:record.breakGlass.reason}); record.breakGlass=null; record.generation++; return this.signEnvelope(record); }
  revokeMembershipForTest(userId,clientId,state='revoked') { const membership=this.memberships.get(`${userId}|${clientId}`); if(!membership) throw new AuthorizationError('MEMBERSHIP_NOT_FOUND'); membership.state=state; }
  revokeRoleForTest(userId,clientId,roleCode) { this.roles.get(`${userId}|${clientId}`)?.delete(roleCode); }
  revokeSession(envelope) { const record=this.parseSession(envelope); record.revoked=true; this.audit('session_revoked',record); }
  validateRedirectPath(value) { if(typeof value!=='string'||!value.startsWith('/')||value.startsWith('//')||value.includes('://')) throw new AuthorizationError('REDIRECT_DENIED'); return value; }
  userState(userId){return this.users.get(userId)?.state ?? 'revoked';} isActiveMembership(userId,clientId){return this.memberships.get(`${userId}|${clientId}`)?.state==='active';}
  firstActiveMembership(userId){return [...this.memberships.entries()].filter(([key,m])=>key.startsWith(`${userId}|`)&&m.state==='active').map(([key])=>key.split('|')[1]).sort()[0] ?? null;}
  permissions(userId,clientId){const roles=[...(this.roles.get(`${userId}|${clientId}`)??new Set()),...(this.roles.get(`${userId}|platform`)??new Set())]; return new Set(roles.flatMap((role)=>permissionMap[role]??[]));}
  audit(event,record,detail={}){this.auditEvents.push({event,actorUserId:record.actorUserId,effectiveUserId:record.effectiveUserId,clientId:record.activeClientId,detail});}
}
