import fs from 'node:fs'; const w=(p,s)=>fs.writeFileSync(p,s);
const risks=[
['Cross-client isolation','TH-04/TH-06','Project and client resources','Authenticated tenant user','Resource ID/query','Cross-client reference','Medium','Critical','Derived scope, membership, non-enumeration','TEST-DENY-001/005','Medium','Security Owner','M-05','E-005/E-011'],
['Excessive administration','TH-06','Platform settings','Privileged user','Admin action','Missing delegation','Medium','High','Named admin delegation, no client content default','TEST-DENY-010','Medium','Operations Owner','M-05','E-005/E-014'],
['Unauthorized approval','TH-02/TH-03/TH-06','Approval and decision','Manager or attacker','Approval endpoint','No authority or self approval','Medium','High','Authority Attribute, SoD, audit','TEST-DENY-008/009','Medium','Governance Owner','M-07','E-008/E-014'],
['Document/download/export leakage','TH-04/TH-08','Document and deliverable','Authorized-looking user','Locator/download/export','Missing source authorization','Medium','Critical','Source check, classification, membership, per-item export','TEST-DENY-006/017/018','Medium','Information Owner','M-08','E-004/E-010'],
['Audit insufficiency or excess logging','TH-03/TH-04','Audit event','User or operator','Audit read/write','Missing minimization or integrity','Medium','High','Append-only capability, scoped read, safe metadata','TEST-DENY-011','Medium','Security Owner','M-07','E-010/E-014'],
['Premature AI activation','TH-01','AI boundary','Operator or code path','AI port','Provider enabled without decision','Low','Critical','Disabled deny-by-default port','TEST-RISK-006','Medium','AI Governance Owner','M-04+','E-012'],
['Retention/deletion uncertainty','TH-03','Archived records','Operator','Archive/delete','Policy absent','Medium','High','Hold, archive proposal, no final delete','TEST-RISK-007','High','Records Owner','M-08','E-010'],
['Search/count leakage','TH-04/TH-05','Search results','Tenant user','Search/query','Filter after match','Medium','High','Scope filter before match/count','TEST-DENY-015','Medium','Security Owner','M-08','E-010'],
['Session/identity abuse','TH-01/TH-06','Identity and membership','Attacker','Session/identity port','Identity policy absent','Medium','Critical','Identity port disabled; server verification design','TEST-RISK-009','High','Security Owner','M-04+','E-005'],
['Injection','TH-07','Command and audit input','Attacker','Future API fields','Unvalidated input','Medium','High','Allowlist validation and safe logging','TEST-RISK-010','Medium','Engineering Owner','M-05','None for design'],
['File/SSRF','TH-08','Storage locator','Attacker','File metadata','Locator trusted as authority','Medium','Critical','Authorization before locator, adapter disabled','TEST-DENY-006/018','High','Security Owner','M-08','E-004'],
['Supply-chain/build scripts','TH-09','Build artifact','Supply-chain attacker','Dependency install','Unreviewed scripts','Low','High','Lockfile, dependency review','TEST-RISK-012','Medium','Engineering Owner','M-09','E-014'],
['Backup/restore exposure','TH-04','Backup set','Operator','Restore process','Weak restore scope','Low','Critical','Scoped restore, approval, audit','TEST-RISK-013','High','Operations Owner','M-09','E-003/E-010'],
['Notification leakage','TH-04','Notification context','Tenant user','Notification port','Recipient scope missing','Medium','High','Recipient scope and disabled channel','TEST-RISK-014','Medium','Operations Owner','M-08','E-006'],
['Race/optimistic concurrency','TH-02','Resource state','Concurrent user','Update/transition','Version conflict','Medium','Medium','Version field and atomic transition','TEST-RISK-015','Low','Engineering Owner','M-06','None for design']];
w('docs/security/m03-risk-register.md',`# سجل المخاطر الدلالي — M-03\n\n| Risk ID | Related Threat IDs | Asset | Threat actor | Entry point | Preconditions | Likelihood | Impact | Inherent rating | Planned controls | Verification/Test IDs | Residual risk | Risk owner | Implementation phase | External dependency | Status | Acceptance authority |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${risks.map((r,i)=>`| MR-${String(i+1).padStart(2,'0')} | ${r.join(' | ')} | Open | Authorized risk authority |`).join('\n')}\n`);
const denies=[
['عميل A يطلب مورد عميل B','PERM-002','TH-04','ASVS mapping verification required'],['Client ID في URL','PERM-002','TH-04','ASVS mapping verification required'],['Client ID في body','PERM-003','TH-02','ASVS mapping verification required'],['Client ID في query','PERM-017','TH-04','ASVS mapping verification required'],['Project ID من عميل آخر','PERM-005','TH-04','ASVS mapping verification required'],['Document ID أو locator معروف','PERM-013','TH-08','ASVS mapping verification required'],['Object Reference عابر للعميل','PERM-007','TH-04','ASVS mapping verification required'],['موافقة بلا سلطة','PERM-010','TH-06','ASVS mapping verification required'],['موافقة ذاتية','PERM-010','TH-06','ASVS mapping verification required'],['Platform Administrator يقرأ عميلًا','PERM-016','TH-06','ASVS mapping verification required'],['Auditor يعدل Audit Event','PERM-015','TH-03','ASVS mapping verification required'],['عضوية منتهية أو مسحوبة','PERM-005','TH-01','ASVS mapping verification required'],['مورد مؤرشف أو مسحوب','PERM-005','TH-02','ASVS mapping verification required'],['تصنيف أعلى من التصريح','PERM-013','TH-04','ASVS mapping verification required'],['بحث أو عداد خارج النطاق','PERM-017','TH-04','ASVS mapping verification required'],['Bulk action يتجاوز المورد','PERM-018','TH-02','ASVS mapping verification required'],['Export يتجاوز الموارد','PERM-018','TH-04','ASVS mapping verification required'],['ملف مرتبط بمورد غير مصرح','PERM-013','TH-08','ASVS mapping verification required']];
w('docs/security/deny-scenarios.md',`# سيناريوهات المنع الدلالية — M-03\n\n| Deny ID | Preconditions | Abuse path | Authorization checks | Expected denial | Non-enumerating response | Audit event | Related Permission IDs | Related Threat IDs | ASVS reference | Test ID | Phase |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n${denies.map((d,i)=>`| DENY-${String(i+1).padStart(2,'0')} | مرجع أو سلطة غير موثوقة | ${d[0]} | نطاق مشتق، عضوية، مورد، حالة، تصنيف، سياسة | Default Deny | RESOURCE_NOT_AVAILABLE | authorization.denied | ${d[1]} | ${d[2]} | ${d[3]} | TEST-DENY-${String(i+1).padStart(3,'0')} | M-05+ |`).join('\n')}\n`);
w('docs/security/abuse-cases.md',`# حالات إساءة الاستخدام الدلالية — M-03\n\n| Abuse ID | Scenario | Related Threat ID | Related Deny ID | Planned verification |\n|---|---|---|---|---|\n${denies.map((d,i)=>`| AB-${String(i+1).padStart(2,'0')} | ${d[0]} | ${d[2]} | DENY-${String(i+1).padStart(2,'0')} | TEST-DENY-${String(i+1).padStart(3,'0')} |`).join('\n')}\n`);
console.log('M03_SEMANTIC_SECURITY_WRITTEN');
