import fs from 'node:fs'; const w=(p,s)=>fs.writeFileSync(p,s);
const perms=[
['ROLE-01','RES-03','ACT-CREATE','Public synthetic intake context only','No Client Scope until future verified conversion','Self-entered synthetic request','No membership; local demo only','CR-DRAFT','Public','None for design','None','Local demo notice','Real submission or storage','E-011','M-05','TEST-PERM-001'],
['ROLE-02','RES-03','ACT-READ','Derived tenant','Derived client','Own request only','Request owner membership active','CR-SUBMITTED/CR-REVIEW','Confidential','None for design','None','Read decision','Other client or request','E-005/E-011','M-06','TEST-PERM-002'],
['ROLE-02','RES-03','ACT-UPDATE','Derived tenant','Derived client','Own request','Owner membership active','CR-DRAFT','Confidential','None','None','Change event','Submitted or other owner','E-011','M-06','TEST-PERM-003'],
['ROLE-05','RES-04','ACT-TRANSITION','Derived tenant','Derived client','Assigned engagement','Project manager assignment','EN-PROPOSED/ACTIVE/PAUSED','Confidential','E-008 when closing','No self-approval','Transition event','Scope or state mismatch','E-008','M-06','TEST-PERM-004'],
['ROLE-02','RES-05','ACT-READ','Derived tenant','Derived client','Project membership','Active project membership','PR-ACTIVE/PAUSED/COMPLETED','Confidential','None','None','Sensitive read when policy','No membership or archived scope','E-005','M-06','TEST-PERM-005'],
['ROLE-04','RES-06','ACT-CREATE','Derived tenant','Derived client','Assigned project','Project membership','PR-ACTIVE','Confidential','None','None','Create work item','Inactive project or outside assignment','None for design','M-06','TEST-PERM-006'],
['ROLE-04','RES-06','ACT-UPDATE','Derived tenant','Derived client','Assigned work item','Assignee or project manager delegation','WI-OPEN/IN-PROGRESS/BLOCKED','Confidential','None','None','Update event','Other project or version conflict','None for design','M-06','TEST-PERM-007'],
['ROLE-05','RES-06','ACT-ASSIGN','Derived tenant','Derived client','Project','Project manager delegation','WI-OPEN/IN-PROGRESS','Confidential','None','No self-escalation','Assignment event','Assignee outside client/project','E-005','M-06','TEST-PERM-008'],
['ROLE-05','RES-07','ACT-CREATE','Derived tenant','Derived client','Project','Project manager assignment','DE-DRAFT','Confidential','None','None','Decision created','No project authority','None for design','M-07','TEST-PERM-009'],
['ROLE-03','RES-08','ACT-APPROVE','Derived tenant','Derived client','Referenced decision/deliverable','Authority Attribute: approval_authority','AP-PENDING','Restricted','E-008','Approver cannot be proposer','Approval result event','No authority or self-approval','E-008/E-014','M-07','TEST-PERM-010'],
['ROLE-03','RES-08','ACT-REJECT','Derived tenant','Derived client','Referenced decision/deliverable','Authority Attribute: approval_authority','AP-PENDING','Restricted','E-008','Approver cannot be proposer','Approval result event','No authority or self-approval','E-008/E-014','M-07','TEST-PERM-011'],
['ROLE-04','RES-09','ACT-DOWNLOAD','Derived tenant','Derived client','Project deliverable','Active membership and source document authorization','DL-APPROVED/DL-DELIVERED','Confidential','None','None','Download decision','Source, classification, or membership fails','E-004/E-010','M-07','TEST-PERM-012'],
['ROLE-04','RES-10','ACT-DOWNLOAD','Derived tenant','Derived client','Document source resource','Active membership and original resource access','DO-EFFECTIVE','Restricted','None','None','Locator issuance event','No locator before authorization','E-004/E-010','M-08','TEST-PERM-013'],
['ROLE-05','RES-11','ACT-PUBLISH','Derived tenant','Derived client','Knowledge item','Knowledge authority Attribute required','KN-IN-REVIEW','Internal','E-008','Publisher not sole reviewer when policy applies','Publish event','No knowledge authority or review state','E-008/E-010','M-08','TEST-PERM-014'],
['ROLE-08','RES-13','ACT-READ','Derived tenant','Explicit review scope','Audit query scope','Reviewer assignment active','Recorded','Restricted','E-014','None','Audit read event','No audit scope','E-014','M-07','TEST-PERM-015'],
['ROLE-07','RES-14','ACT-ADMINISTER','Platform tenant only','None for client content','Named platform setting','Platform admin delegation','Active','Internal','E-014','None','Admin event','Client content or unapproved setting','E-014','M-05','TEST-PERM-016'],
['ROLE-04','RES-11','ACT-SEARCH','Derived tenant','Derived client','Authorized knowledge scope','Membership and classification filter','KN-APPROVED','Internal','None','None','Search decision','Filter before match/count','E-010','M-08','TEST-PERM-017'],
['ROLE-03','RES-09','ACT-EXPORT','Derived tenant','Derived client','Approved deliverables only','Export authority Attribute required','DL-DELIVERED','Confidential','E-008','None','Export event','Any unauthorized item aborts action','E-004/E-008/E-010','M-08','TEST-PERM-018']];
const headers=['Permission ID','Role ID','Resource ID','Action ID','Tenant Scope','Client Scope','Object/Project Scope','Ownership/Membership Requirement','Business State Condition','Classification Condition','Approval Requirement','Separation-of-Duties Condition','Audit Requirement','Deny Condition','External Decision','Implementation Phase','Verification/Test ID'];
w('docs/security/permission-matrix.md',`# مصفوفة الصلاحيات الدلالية — M-03\n\n| ${headers.join(' | ')} |\n|${headers.map(()=> '---').join('|')}|\n${perms.map((r,i)=>`| PERM-${String(i+1).padStart(3,'0')} | ${r.join(' | ')} |`).join('\n')}\n\nغياب أي صف Allow يعني **Default Deny**. لا يمثل Authority Attribute دوراً جديداً.\n`);
w('docs/security/permission-coverage-matrix.md',`# تغطية الصلاحيات الدلالية — M-03\n\n| Role ID | Resource ID | Action ID | Allow condition | Explicit deny | Test requirement |\n|---|---|---|---|---|---|\n${perms.map(r=>`| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]}؛ ${r[6]} | ${r[12]} | ${r[16]} |`).join('\n')}\n\nغياب الصف يعني Default Deny.\n`);
const machines={
'Consultation Request':[['CR-DRAFT','CR-SUBMITTED','ACT-SUBMIT','ROLE-02'],['CR-SUBMITTED','CR-REVIEW','ACT-START-REVIEW','ROLE-05'],['CR-REVIEW','CR-ACCEPTED','ACT-ACCEPT','ROLE-05'],['CR-REVIEW','CR-DECLINED','ACT-DECLINE','ROLE-05'],['CR-SUBMITTED','CR-WITHDRAWN','ACT-WITHDRAW','ROLE-02'],['CR-REVIEW','CR-WITHDRAWN','ACT-WITHDRAW','ROLE-02'],['CR-ACCEPTED','CR-CLOSED','ACT-CLOSE','ROLE-05'],['CR-DECLINED','CR-CLOSED','ACT-CLOSE','ROLE-05']],
Engagement:[['EN-PROPOSED','EN-ACTIVE','ACT-ACTIVATE','ROLE-05'],['EN-ACTIVE','EN-PAUSED','ACT-PAUSE','ROLE-05'],['EN-PAUSED','EN-ACTIVE','ACT-RESUME','ROLE-05'],['EN-ACTIVE','EN-CLOSED','ACT-CLOSE','ROLE-05'],['EN-PAUSED','EN-CLOSED','ACT-CLOSE','ROLE-05']],
Project:[['PR-PROPOSED','PR-ACTIVE','ACT-ACTIVATE','ROLE-05'],['PR-ACTIVE','PR-PAUSED','ACT-PAUSE','ROLE-05'],['PR-PAUSED','PR-ACTIVE','ACT-RESUME','ROLE-05'],['PR-ACTIVE','PR-COMPLETED','ACT-COMPLETE','ROLE-05'],['PR-COMPLETED','PR-ARCHIVED','ACT-ARCHIVE','ROLE-07']],
'Work Item':[['WI-OPEN','WI-IN-PROGRESS','ACT-START','ROLE-04'],['WI-IN-PROGRESS','WI-BLOCKED','ACT-BLOCK','ROLE-04'],['WI-BLOCKED','WI-IN-PROGRESS','ACT-RESUME','ROLE-04'],['WI-IN-PROGRESS','WI-IN-REVIEW','ACT-SUBMIT-REVIEW','ROLE-04'],['WI-IN-REVIEW','WI-IN-PROGRESS','ACT-REQUEST-CHANGES','ROLE-05'],['WI-IN-REVIEW','WI-DONE','ACT-COMPLETE','ROLE-05'],['WI-OPEN','WI-CANCELLED','ACT-CANCEL','ROLE-05'],['WI-IN-PROGRESS','WI-CANCELLED','ACT-CANCEL','ROLE-05']],
Decision:[['DE-DRAFT','DE-PROPOSED','ACT-PROPOSE','ROLE-05'],['DE-PROPOSED','DE-UNDER-REVIEW','ACT-SEND-REVIEW','ROLE-05'],['DE-UNDER-REVIEW','DE-APPROVED','ACT-APPROVE','ROLE-03'],['DE-UNDER-REVIEW','DE-REJECTED','ACT-REJECT','ROLE-03'],['DE-DRAFT','DE-WITHDRAWN','ACT-WITHDRAW','ROLE-05'],['DE-PROPOSED','DE-WITHDRAWN','ACT-WITHDRAW','ROLE-05']],
Approval:[['AP-REQUESTED','AP-PENDING','ACT-REQUEST','ROLE-05'],['AP-PENDING','AP-APPROVED','ACT-APPROVE','ROLE-03'],['AP-PENDING','AP-REJECTED','ACT-REJECT','ROLE-03'],['AP-PENDING','AP-EXPIRED','ACT-EXPIRE','ROLE-06'],['AP-REQUESTED','AP-WITHDRAWN','ACT-WITHDRAW','ROLE-05']],
Deliverable:[['DL-DRAFT','DL-IN-REVIEW','ACT-SUBMIT-REVIEW','ROLE-04'],['DL-IN-REVIEW','DL-APPROVED','ACT-APPROVE','ROLE-03'],['DL-APPROVED','DL-DELIVERED','ACT-DELIVER','ROLE-05'],['DL-DELIVERED','DL-ARCHIVED','ACT-ARCHIVE','ROLE-07']],
Document:[['DO-DRAFT','DO-IN-REVIEW','ACT-SUBMIT-REVIEW','ROLE-04'],['DO-IN-REVIEW','DO-EFFECTIVE','ACT-EFFECT','ROLE-05'],['DO-EFFECTIVE','DO-SUPERSEDED','ACT-SUPERSEDE','ROLE-05'],['DO-EFFECTIVE','DO-ARCHIVED','ACT-ARCHIVE','ROLE-07'],['DO-EFFECTIVE','DO-RETENTION-HOLD','ACT-PLACE-HOLD','ROLE-07']],
'Knowledge Item':[['KN-DRAFT','KN-IN-REVIEW','ACT-SUBMIT-REVIEW','ROLE-04'],['KN-IN-REVIEW','KN-APPROVED','ACT-PUBLISH','ROLE-05'],['KN-APPROVED','KN-ARCHIVED','ACT-ARCHIVE','ROLE-07']],
Membership:[['MB-INVITED','MB-ACTIVE','ACT-ACTIVATE','ROLE-07'],['MB-ACTIVE','MB-SUSPENDED','ACT-SUSPEND','ROLE-07'],['MB-SUSPENDED','MB-ACTIVE','ACT-REACTIVATE','ROLE-07'],['MB-ACTIVE','MB-REVOKED','ACT-REVOKE','ROLE-07'],['MB-SUSPENDED','MB-REVOKED','ACT-REVOKE','ROLE-07']]};
const resMap={'Consultation Request':'RES-03',Engagement:'RES-04',Project:'RES-05','Work Item':'RES-06',Decision:'RES-07',Approval:'RES-08',Deliverable:'RES-09',Document:'RES-10','Knowledge Item':'RES-11',Membership:'RES-02'};
let sections=[];let n=0;for(const [name,trs] of Object.entries(machines)){sections.push(`## ${name} — ${resMap[name]}\n\n| Transition ID | Resource ID | From State | To State | Trigger/Action | Allowed Role IDs | Authority/Scope Condition | Preconditions | Approval Requirement | Separation-of-Duties Requirement | Audit Event | Invalid-transition response | Reversal/Withdrawal behavior | Retention effect | External Decision | Implementation Phase | Test ID |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${trs.map(t=>`| TR-${String(++n).padStart(3,'0')} | ${resMap[name]} | ${t[0]} | ${t[1]} | ${t[2]} | ${t[3]} | نطاق مشتق وسلطة مورد | حالة ومورد وإصدار مطابق | ${t[2].includes('APPROVE')||t[2].includes('REJECT')?'E-008':'None for design'} | ${t[2].includes('APPROVE')||t[2].includes('REJECT')?'لا ذاتية':'لا ينطبق'} | ${name}.transitioned | STATE_TRANSITION_NOT_ALLOWED | قرار أو حدث جديد؛ لا قلب قرار طرفي | Retention policy required | E-008/E-010 | M-06+ | TEST-TR-${String(n).padStart(3,'0')} |`).join('\n')}\n\nالحالات الطرفية: ${name==='Membership'?'MB-EXPIRED وMB-REVOKED':trs.map(x=>x[1]).filter(s=>!trs.some(t=>t[0]===s)).join('، ')||'حسب السياسة'}.\n\n\`\`\`mermaid\nstateDiagram-v2\n${trs.map(t=>`${t[0]} --> ${t[1]}: ${t[2]}`).join('\n')}\n\`\`\`\n`);}w('docs/architecture/state-machines.md',`# آلات الحالة الدلالية — M-03\n\n${sections.join('\n')}`);
const names=['tenants','organizations','users','identities','memberships','role_assignments','consultation_requests','engagements','projects','project_memberships','work_items','decisions','approvals','deliverables','documents','document_versions','knowledge_items','notifications','audit_events','policy_decisions'];
const meta={identities:['مرجع هوية خارجي مستقبلي','identity_id','لا ينطبق','users','حالة تحقق','None','E-005'],role_assignments:['منح دور ونطاق ومدة','role_assignment_id','حسب membership','memberships','حالة فعالة','Internal','E-005'],project_memberships:['صلة مشروع وعضوية','project_membership_id','مطلوب','projects + memberships','حالة فعالة','Confidential','E-005'],document_versions:['إصدار تابع لوثيقة أصلية','document_version_id','مطلوب','documents','حالة نسخة','Restricted','E-004/E-010'],notifications:['نية إخطار لمستلم محدد','notification_id','مطلوب','recipient membership','حالة قراءة','Confidential','E-006'],audit_events:['أثر قرار مختزل','audit_event_id','مطلوب','audited aggregate','مسجل/محفوظ','Restricted','E-010/E-014'],policy_decisions:['نتيجة تقييم سياسة بلا سر','policy_decision_id','مطلوب','resource + policy version','مسجل','Internal','E-008']};
w('docs/data/data-dictionary.md',`# قاموس البيانات الدلالي — M-03\n\n| Entity ID | Entity | Purpose | Primary identifier | Tenant boundary | Client boundary | Owner/aggregate | Required relationships | Lifecycle state field | Classification field | Created/updated metadata | Concurrency/version field | Archive/soft-delete proposal | Retention dependency | Audit dependency | Conceptual unique constraints | Forbidden relationships | External Decisions |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${names.map((x,i)=>{let m=meta[x]||[`سجل ${x} ضمن المجال`,` ${x.slice(0,-1)}_id`.trim(),['tenants','users'].includes(x)?'لا ينطبق':'مطلوب',x==='tenants'?'منصة':x==='organizations'?'tenants':'organization أو project','state مناسب','Internal/Confidential','E-010'];return `| ENT-${String(i+1).padStart(2,'0')} | ${x} | ${m[0]} | ${m[1]} | ${x==='tenants'?'ذاتي':'مشتق'} | ${m[2]} | ${m[3]} | tenant + علاقات نطاق صريحة | ${m[4]} | ${m[5]} | created_at / updated_at | version | archive proposal | ${m[6]} | حدث آمن عند الفعل الحساس | مفتاح منطقي ضمن النطاق | اختلاف client أو locator كسلطة أو تعديل audit | ${m[6]} |`;}).join('\n')}\n`);
console.log('M03_SEMANTIC_DOCS_WRITTEN');
