import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const rules = [
  ["M06-A01", /findAll\(/], ["M06-A02", /use client[\s\S]*(?:m06repo|\.\/repository|\.\/service)/], ["M06-A03", /localStorage|sessionStorage/], ["M06-A04", /fetch\(['"]https?:/], ["M06-A05", /prisma|typeorm|mongoose/], ["M06-A06", /provider-sdk/], ["M06-A07", /audit[^\n]*(summary|description)/], ["M06-A08", /transition[A-Za-z]*\([^)]*next[^)]*\)(?![\s\S]*expectedVersion)/], ["M06-A09", /update[A-Za-z]*\([^)]*\)(?![\s\S]*version)/], ["M06-A10", /clientId.*searchParams|tenantId.*searchParams/], ["M06-A11", /ADMIN.*(REQUESTS|PROJECTS)/], ["M06-A12", /portal\/decisions|portal\/approvals/], ["M06-A13", /https:\/\/fonts\.|fonts\.googleapis/], ["M06-A14", /font-family:\s*(?:Inter|Arial|Helvetica|Segoe)/], ["M06-A15", /\.filter\([^)]*scope[^)]*\).*React/], ["M06-A16", /transition[A-Za-z]*\([^)]*\)[\s\S]*state\s*=/], ["M06-A17", /assignWork\([^)]*outside/]
];
const walk = d => !fs.existsSync(d) ? [] : fs.readdirSync(d, { withFileTypes: true }).flatMap(e => { const p = path.join(d, e.name); return e.isDirectory() ? walk(p) : /\.(ts|tsx|css)$/.test(p) ? [p] : []; });
export function scanProject(root) { return [...walk(path.join(root, "src/m06")), ...walk(path.join(root, "app")).filter(f => !f.endsWith("globals.css") && !f.endsWith("global-error.tsx"))].flatMap(f => { const s = fs.readFileSync(f, "utf8"); return rules.filter(([, r]) => r.test(s)).map(([c]) => `${c}:${path.relative(root, f)}`); }); }
const samples = ["findAll(", "'use client'; import { m06repo } from './repository'", "localStorage", "fetch('https:", "prisma", "provider-sdk", "audit summary", "transitionWork(next)", "updateWork()", "clientId searchParams", "ADMIN REQUESTS", "portal/decisions", "https://fonts.googleapis", "font-family: Inter", ".filter(scope) React", "transitionWork() state =", "assignWork(outside)"];
if (process.argv[1] === fileURLToPath(import.meta.url)) { const root = path.resolve(process.argv[2] || "."); const hits = scanProject(root); if (hits.length) { console.error(hits.join("\n")); process.exit(2); } const base = fs.mkdtempSync(path.join(os.tmpdir(), "m06-fixtures-")); for (let i = 0; i < rules.length; i++) { const [code] = rules[i], d = path.join(base, code, "src/m06"); fs.mkdirSync(d, { recursive: true }); fs.writeFileSync(path.join(d, "bad.ts"), samples[i]); if (!scanProject(path.join(base, code)).some(h => h.startsWith(code + ":"))) { console.error(`fixture ${code} failed`); process.exit(3); } } console.log(`M06_ARCHITECTURE_PASS rules=${rules.length} fixtureProjects=${rules.length}`); }
